### ISSUE TITLE
Downloading error

### ISSUE THREAD

**Issue by pjduplooy** [cartologic/cartoview#10]
Hi guys, Sorry to post this on github, but I have send you an email, but no response yet.

After registration, when I click on the download link for 1.5 in my email, I get the following error that starts like this:

MemoryError at /download/fff6558c-a7c3-47bb-b26b-cfb39e47db78/Cartoview_1.5.exe

No exception message supplied

Request Method: 	GET
Request URL: 	http://localhost:4042/cartoview/download/fff6558c-a7c3-47bb-b26b-cfb39e47db78/Cartoview_1.5.exe
Django Version: 	1.10.3
Exception Type: 	MemoryError
Exception Location: 	C:\WEB\cartoview_website\env\Lib\site-packages\django\http\response.py in content, line 319
Python Executable: 	C:\Cartoview\apache24\bin\httpd.exe
Python Version: 	2.7.10
Python Path: 	

['C:\\WEB\\cartoview_website\\env\\Lib\\site-packages',
 'C:\\Cartoview\\python\\Lib\\site-packages\\django_bootstrap3_datetimepicker-2.2.3-py2.7.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\gsimporter-1.0.0-py2.7.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\gsconfig-1.0.3-py2.7.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\geonode_dialogos-0.4-py2.7.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\geonode_arcrest-10.2-py2.7.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\django_mptt-0.6.1-py2.7.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\awesome_slugify-1.6.2-py2.7.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\multipartposthandler-0.1.0-py2.7.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\beautifulsoup4-4.2.1-py2.7.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\pillow-3.1.1-py2.7-win32.egg',
 'C:\\Cartoview\\python\\Lib\\site-packages\\pytz-2015.7-py2.7.egg',
 'C:\\Cartoview\\cartoview',
 'C:\\Cartoview\\Python\\lib\\site-packages\\geonode-2.4-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\pep8-1.6.2-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\flake8-2.3.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_bootstrap3_datetimepicker-2.2.3-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_celery-3.1.16-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\celery-3.1.17-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\pyelasticsearch-0.6.1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_haystack-2.1.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\pycsw-1.10.3-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\owslib-0.10.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\gisdata-0.5.4-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\gsimporter-1.0.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\gsconfig-1.0.3-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\geonode_dialogos-0.4-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\geonode_notification-1.1.1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\geonode_arcrest-10.2-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\geonode_user_accounts-1.0.10-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\geonode_agon_ratings-0.3.1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\geonode_announcements-1.0.5-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\geonode_avatar-2.1.4-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\geonode_user_messages-0.1.2-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_geoexplorer-4.0.5-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_modeltranslation-0.8-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_autocomplete_light-2.2.10-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_leaflet-0.13.7-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_polymorphic-0.5.6-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_tastypie-0.11.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_downloadview-1.2-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_activity_stream-0.4.5b1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_friendly_tag_loader-1.1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_forms_bootstrap-3.0.1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\pinax_theme_bootstrap_account-1.0b2-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\pinax_theme_bootstrap-3.0a11-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_guardian-1.2.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_mptt-0.6.1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_taggit-0.12-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_extensions-1.2.5-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_jsonfield-0.9.12-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_pagination-1.0.7-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\awesome_slugify-1.6.2-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django_nose-1.2-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\nose-1.0.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\paver-1.2.1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\py2exe-0.6.9-py2.7-win32.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\transifex_client-0.10-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\httplib2-0.8-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\multipartposthandler-0.1.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\beautifulsoup4-4.2.1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\pillow-3.1.1-py2.7-win32.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\mccabe-0.4.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\pyflakes-1.0.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\kombu-3.0.33-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\billiard-3.3.0.22-py2.7-win32.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\pytz-2015.7-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\six-1.10.0-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\simplejson-3.8.1-py2.7-win32.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\requests-2.9.1-py2.7.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\shapely-1.3.1-py2.7-win32.egg',
 'C:\\Cartoview\\Python\\lib\\site-packages\\pyproj-1.9.3-py2.7-win32.egg',
 'C:\\Cartoview\\apache24\\bin\\python27.zip',
 'C:\\Cartoview\\Python\\DLLs',
 'C:\\Cartoview\\Python\\lib',
 'C:\\Cartoview\\Python\\lib\\plat-win',
 'C:\\Cartoview\\Python\\lib\\lib-tk',
 'C:\\Cartoview\\apache24\\bin',
 'C:\\Cartoview\\Python',
 'C:\\Cartoview\\Python\\lib\\site-packages',
 'C:\\WEB\\cartoview_website']

Could you please investigate?

Pieter

**Comment by hishamkaram** [comment]
Hi Pieter
you can download installer from this link
http://cartologic.com/cartoview/new/static/Cartoview_1.5.exe
<http://www.google.com/url?q=http%3A%2F%2Fcartologic.com%2Fcartoview%2Fnew%2Fstatic%2FCartoview_1.5.exe&sa=D&sntz=1&usg=AFQjCNG6lc6PQnyJeMTBxSmB4RaBAGZ7bw>

we are working on a fix to this issue
Thank you for  for reporting


Hisham
