### ISSUE TITLE
Documentation and Download error

### ISSUE THREAD

**Issue by pjduplooy** [cartologic/cartoview#11]
Hi guys

I am trying to read the cartoview docs, as well as to go to the download page.  The pages are:

http://cartoview.readthedocs.io/en/latest/index.html, and http://cartoview.readthedocs.io/en/latest/installation/index.html

On the docs page I get:

Welcome to Read the Docs

This is an autogenerated index file.

Please create a /home/docs/checkouts/readthedocs.org/user_builds/cartoview/checkouts/latest/docs/index.rst or /home/docs/checkouts/readthedocs.org/user_builds/cartoview/checkouts/latest/docs/README.rst file with your own content.

If you want to use another markup, choose a different builder in your settings.

and on the install page I get 

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

Please help....

**Comment by hishamkaram** [comment]
Hi @pjduplooy 
please use this [link](http://caartoview.readthedocs.io/en/latest/) Temporarily.
we will fix this issue
Thanks.

**Comment by hishamkaram** [comment]
we updated the documentation now you can use the new one [here](http://cartologic.github.io/cartoview/)
**note: [readthedocs](http://cartoview.readthedocs.io/en/latest/) deprecated**

**Comment by hishamkaram** [comment]
@pjduplooy
