### ISSUE TITLE
Unable to install "Cartoview TerriaMap Viewer" app

### ISSUE THREAD

**Issue by khaledboka** [cartologic/cartoview#111]
<img width="1440" alt="screen shot 2017-12-07 at 11 16 21 am" src="https://user-images.githubusercontent.com/13452248/33707479-254a77e6-db40-11e7-85c8-02d0a7cb0817.png">

**Comment by ahmednoureldeen** [comment]
Issue moved to [cartologic/cartoview_terriaJs #1](https://github.com/cartologic/cartoview_terriaJs/issues/1) via [**ZenHub**](https://www.zenhub.com/)
