### ISSUE TITLE
Cartoview in OsgeoLive

### ISSUE THREAD

**Issue by pjduplooy** [cartologic/cartoview#125]
Hi guys

This is not an issue, but rather an question.  Would it be possible to install Cartoview in the OsgeoLive distribution?  

Has anyone attempted it?  I would like to do it, but the instructions is a bit confusing to me to get an install right in Ubuntu.

Can I install Cartoview after installing Geonode from PPA (Geonode PPA) as done on OsgeoLIVE?

Any help and guidance would be appreciated!!

**Comment by hishamkaram** [comment]
here is the guide https://github.com/cartologic/cartoview/issues/140#issuecomment-361968657
