### ISSUE TITLE
correction required in documentation for ubuntu installation

### ISSUE THREAD

**Issue by vinayak1411** [cartologic/cartoview#135]
django-admin.py startproject template=https://github.com/cartologic/Cartoview-project-template/archive/master.zip --name django.env,uwsgi.ini,.bowerrc,server.py <your_project_name>

this gives an error

so it should be replaced by

django-admin.py startproject --template=https://github.com/cartologic/Cartoview-project-template/archive/master.zip --name django.env,uwsgi.ini,.bowerrc,server.py <project name>

**Comment by hishamkaram** [comment]
fixed
