### ISSUE TITLE
Cartoview Windows 1.7

### ISSUE THREAD

**Issue by pjduplooy** [cartologic/cartoview#136]
Hi guys.

I just want to find out what the prerequisites are for installing using the Windows installer.  When I install on a clean system, do I download jre or jdk?  as on a clean system and on a system that has a jdk, tomcat does not work.  In the installer it states that 64 bit is needed.  Is that correct? Is Python necessary?  also if so, 64 bit?

I already have Postgres 10 installed as well as Python.  The carto db's are created.  When I try to launch Tomcat from Windows Services this is the error I get:

The CARTOVIEW_TOMCAT_4041 service terminated with the following service-specific error: 
Incorrect function.

Anyone seen this?

Any help would be highly appreciated.

Also, when I run the tomcat8w (the config manager), I get 
![capture](https://user-images.githubusercontent.com/127220/34378568-1ced26f6-eaff-11e7-87b3-064298ae748d.JPG)

Pieter

**Comment by ahmednoureldeen** [comment]
Cartoview windows Installer need jdk or jre 1.8 or higher 64.
make sure that JAVA_HOME is set correctly to C:\Program Files\Java\jdk1.8.0_144 or C:\Program Files\Java\jre_folder\bin

**Comment by pjduplooy** [comment]
Hi

Your answer refers.  I have uninstalled all versions of JDK and JRE, and installed JDK 1.8.0_144.
 JAVA_HOME is set as C:\Program Files\Java\jdk1.8.0_144.

Service still does not start.

Anything else that you can think of?

**Comment by pjduplooy** [comment]
Hi guys.

Sorry to bother...

Any further help or info you can give me?

Pieter

**Comment by hishamkaram** [comment]
Hello @pjduplooy @ahmednoureldeen @ahmednosman 
Sorry for my late reply.
We will release a New Version of Windows Installer next week.
Thanks

**Comment by pjduplooy** [comment]
Hi there.  Could you possibly give an indication of date next week?  I might be able to include Cartoview in a presentation I am giving next week.

Also what version of Geonode is included?

**Comment by ahmednoureldeen** [comment]
we will release latest cartoview with geonode 2.7.4 in 16/1/2018. but kindly try the following instruction to help cartoview windows installer get better:

1. open command line as administrator
2. run `sc delete CARTOVIEW_TOMCAT_4041`
3. run `cd "C:\Program Files (x86)\cartoview\setup scripts\start_geoserver.bat"`

and send to me  the command line window as screenshot 

thanks

**Comment by pjduplooy** [comment]
Hi

I did as requested.  

1.  Ran sc delete CARTOVIEW_TOMCAT_4041
1.  Confirmed that tomcat was removed from services "plugin"
2.  Did a cd to C:\Program Files (x86)\cartoview\setup scripts
3.  Ran start_geoserver.bat
4.  After this I noticed that tomcat service was installed in services, although there was an error in command line.

Attached are 3 screenshots.  Two of them the services plugin (after sc delete, and after start_geoserver), and the command line output

Pieter
![after_sc_delete](https://user-images.githubusercontent.com/127220/34919234-d5bd1f5c-f968-11e7-8102-e63d73cf9f54.JPG)
![after_start_geoserver](https://user-images.githubusercontent.com/127220/34919235-d5f49716-f968-11e7-813f-5e19af187d67.JPG)
![output_after_start_geoserver](https://user-images.githubusercontent.com/127220/34919236-d629db1a-f968-11e7-85e0-1993c30d9fce.JPG)

**Comment by ahmednoureldeen** [comment]
Thanks a lot for your feedback.
Replace C:\Program Files (x86)\cartoview\tomcat 8.0\service.bat by this [service.zip](https://github.com/cartologic/cartoview/files/1630404/service.zip).
it will get your installed version working and we will fix the issue in the next release.

**Comment by pjduplooy** [comment]
Thanx a million.  Its working now!!

**Comment by pjduplooy** [comment]
Hi

Just wanna find out if 1.8 is ready for download yet?

**Comment by ahmednosman** [comment]
unfortunately we had to postpone this release for a while, since we have some issues to resolve first

**Comment by pjduplooy** [comment]
Not a problem. Good luck in resolving it

**Comment by pjduplooy** [comment]
Any news on 1.8?

**Comment by ahmednoureldeen** [comment]
geonode 2.8 is about to be released soon, and we need to release with this stable version
I hope 1.7 is working fine.

**Comment by jitendrashahiitb** [comment]
Have installed geonode 2.8 . working fine. Now waiting for cartoview that is compatible.
