### ISSUE TITLE
roadmap for cartoview on geonode 2.8 : dates

### ISSUE THREAD

**Issue by jitendrashahiitb** [cartologic/cartoview#141]
## Please fill the following information to avoid closing issue

Waiting for install instruction (and code) for cartoview as compatible with geonode 2.8 rc11 ( testing) 

- Cartoview Version : (x.xx.x)
- Geonode Version : (2.8.rc11)
- log (optional):
```
```

**Comment by hishamkaram** [comment]
Hello @jitendrashahiitb 
_geonode `2.8`still unstable , we are waiting for the stable version._

**Comment by hishamkaram** [comment]
you can also check the progress of (cartoview + geonode2.8) integration from here 
https://github.com/cartologic/cartoview/tree/2.8.x_integeration

**Comment by jondoig** [comment]
@hishamkaram that's a 404

**Comment by hishamkaram** [comment]
hello @jondoig 
sorry for being late 
it's now on master
you can clone [master branch](https://github.com/cartologic/cartoview/tree/master) then  `cd` to the repo and run `pip install -e . `

**Comment by hishamkaram** [comment]
@jondoig please check [the docs](https://github.com/cartologic/cartoview/blob/master/README.md)
