### ISSUE TITLE
show geoApp Market in Cartoview

### ISSUE THREAD

**Issue by leslie971** [cartologic/cartoview#142]
- Geonode Version : (2.6.3)

I followed the steps of the tutorial (http://cartologic.github.io/installation_ubuntu/) but I can not access to the geo market 
connect with admin , the page is empty when I click on the button manage apps
I installed nodejs and bower

did I forget a step ?

Thanks

**Comment by hishamkaram** [comment]
Hello @leslie971 
please can you send me the following information:
-  open admin panel (App_Manager › App stores › Cartoview App Store)  and take a screenshot from app store recode as the following
![screen shot 2018-02-06 at 4 12 33 pm](https://user-images.githubusercontent.com/24391550/35863837-95c638c8-0b58-11e8-94c6-ec1489a2292b.png)

- open manage apps page and right click in empty place then select inspect element and open console tab and take a screenshot
![screen shot 2018-02-06 at 4 15 12 pm](https://user-images.githubusercontent.com/24391550/35863951-f851eb36-0b58-11e8-9d66-0d96ab3c9054.png)

- send me log from django console or apache log

**Comment by leslie971** [comment]
[cid:10052C0E-2B8C-496F-9A8E-FB1A36236F08@univ-ag.fr]

The « empty »  page

[cid:CFFF259C-36D9-4051-933A-DE037FA17E4F@univ-ag.fr]







Le 6 févr. 2018 à 10:16, Hisham waleed karam <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hello @leslie971<https://github.com/leslie971>
please can you send me the following information:

  *   open admin panel (App_Manager › App stores › Cartoview App Store) and take a screenshot from app store recode as the following
[screen shot 2018-02-06 at 4 12 33 pm]<https://user-images.githubusercontent.com/24391550/35863837-95c638c8-0b58-11e8-94c6-ec1489a2292b.png>

  *   open manage apps page and right click in empty place then select inspect element and open console tab and take a screenshot
[screen shot 2018-02-06 at 4 15 12 pm]<https://user-images.githubusercontent.com/24391550/35863951-f851eb36-0b58-11e8-9d66-0d96ab3c9054.png>

  *   send me log from django console or apache log

**Comment by hishamkaram** [comment]
please update your comment and fix images

**Comment by leslie971** [comment]
cartoview  Version: 1.4.4

<img width="1232" alt="capture1" src="https://user-images.githubusercontent.com/36196863/35865541-28614a02-0b2b-11e8-8076-6b12aadd4f30.png">


[0.0.0.0-1517928278339.log](https://github.com/cartologic/cartoview/files/1699479/0.0.0.0-1517928278339.log)

**Comment by hishamkaram** [comment]
click on manage apps to install apps

**Comment by leslie971** [comment]
the log file shows the state of cartoview when I click on manage apps

<img width="1225" alt="capture2" src="https://user-images.githubusercontent.com/36196863/35866830-8e2d2452-0b2e-11e8-95af-3e2b7d017c6f.png">

**Comment by hishamkaram** [comment]
try to run this command in your project folder 
`bower install `
then refresh this tab

**Comment by hishamkaram** [comment]
try to open this url` localhost:8000/apps/manage`

**Comment by leslie971** [comment]
The node binary was not on my $PATH and the command ( bower install) didn't work
I fixed that. Now it's work .Thanks

**Comment by hishamkaram** [comment]
You are welcome
