### ISSUE TITLE
 add cartoview (latest, compatible ) apps to an existing geonode 2.6.3

### ISSUE THREAD

**Issue by jitendrashahiitb** [cartologic/cartoview#147]
how to add cartoview (latest, compatible ) apps to an existing geonode installation after cloning cartoview from github

- Cartoview Version : (x.xx.x)
- Geonode Version : (2.6.3)
- log (optional):

**Comment by hishamkaram** [comment]
@jitendrashahiitb please check [installation instructions](https://github.com/cartologic/cartoview/blob/master/README.md)
