### ISSUE TITLE
Error installing Cartoview

### ISSUE THREAD

**Issue by jitendrashahiitb** [cartologic/cartoview#15]
OS : Ubuntu 16.04 
Command : pip3 install cartoview
Collecting cartoview
  Using cached cartoview-1.1.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_u3uxfs4/cartoview/setup.py", line 5, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "/home/jitendra/.local/lib/python3.5/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

**Comment by hishamkaram** [comment]
you are using python3 and cartoview compatible  with python2 only

**Comment by hishamkaram** [comment]
please [read the docs](cartologic.github.io)
```
Collecting cartoview
  Downloading cartoview-1.1.13.tar.gz (973kB)
    100% |################################| 983kB 7.8MB/s 
Installing collected packages: cartoview
  Running setup.py install for cartoview ... done
Successfully installed cartoview-1.1.13
```

**Comment by jitendrashahiitb** [comment]
thanks a lot.
