### ISSUE TITLE
unable to install on ubuntu 16.04

### ISSUE THREAD

**Issue by killertonez** [cartologic/cartoview#156]
pip install cartoview
```
Requirement already satisfied: cartoview in ./geonode/lib/python2.7/site-packages (1.8.1)
Requirement already satisfied: six==1.10.0 in ./geonode/lib/python2.7/site-packages (from cartoview) (1.10.0)
Requirement already satisfied: future in ./geonode/lib/python2.7/site-packages (from cartoview) (0.16.0)
django-polymorphic 2.0.2 has requirement Django>=1.11, but you'll have django 1.8.19 which is incompatible.
pyelasticsearch 1.4.1 has requirement elasticsearch<2.0.0,>=1.3.0, but you'll have elasticsearch 6.2.0 which is incompatible.
pycsw 2.2.0 has requirement lxml==3.6.2, but you'll have lxml 4.2.1 which is incompatible.
django-haystack 2.8.1 has requirement Django>=1.11, but you'll have django 1.8.19 which is incompatible.
pinax-theme-bootstrap-account 1.0b2 has requirement django-appconf==0.5, but you'll have django-appconf 1.0.2 which is incompatible.
```

Running pip install cartoview i get that error

**Comment by ahmednoureldeen** [comment]
It seems you have already geonode installed , so make sure that geonode is working fine as all these conflicts related to geonode.
to solve this conflicts install geonode requirements using 
`pip install -r <geonode_requirements>.txt`

**Comment by lolob** [comment]
I got the same problem during  `pip install cartoview`

> pinax-theme-bootstrap-account 1.0b2 has requirement django-appconf==0.5, but you'll have django-appconf 1.0.2 which is incompatible.
> pyelasticsearch 1.4 has requirement elasticsearch<2.0.0,>=1.3.0, but you'll have elasticsearch 5.4.0 which is incompatible.
> pycsw 2.0.3 has requirement lxml==3.6.2, but you'll have lxml 3.8.0 which is incompatible.
> pycsw 2.0.3 has requirement OWSLib==0.10.3, but you'll have owslib 0.14.0 which is incompatible.
> pycsw 2.0.3 has requirement pyproj==1.9.3, but you'll have pyproj 1.9.5.1 which is incompatible.
> pycsw 2.0.3 has requirement Shapely==1.3.1, but you'll have shapely 1.5.17.post1 which is incompatible.

Probably just warning. Then I proceed until `python manage.py makemigrations app_manager` for first time. Now the error;

> `/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/geonode/catalogue/__init__.py:27: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
>   from django.utils.importlib import import_module
> 
> /home/az/.virtualenvs/newenv/lib/python2.7/site-packages/dialogos/models.py:6: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
>   from django.contrib.contenttypes.generic import GenericForeignKey
> 
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
>     django.setup()
>   File "/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
>     app_config.import_models(all_models)
>   File "/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/geonode/base/models.py", line 56, in <module>
>     from geonode.utils import bbox_to_wkt
>   File "/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/geonode/utils.py", line 30, in <module>
>     from osgeo import ogr
>   File "/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
>     _gdal = swig_import_helper()
>   File "/home/az/.virtualenvs/newenv/lib/python2.7/site-packages/osgeo/__init__.py", line 13, in swig_import_helper
>     import _gdal
> ImportError: No module named _gdal

Can someone share `requirements.txt` that is working.

**Comment by ahmednoureldeen** [comment]
To install gdal in virtualenv do the following steps:
```
$ sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
$ sudo apt-get update
$ sudo apt-get install libgdal-dev
```
activate the virtualenv source `newenv/bin/activate`

`pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal" `

**Comment by lolob** [comment]
Thanks. The above gdal is okay now. But a new one now; 

> (sabahenv) az@ubuntusab:~/proj_sab$ python manage.py makemigrations app_manager
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/az/.virtualenvs/sabenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/home/az/.virtualenvs/sabenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
>     django.setup()
>   File "/home/az/.virtualenvs/sabenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/az/.virtualenvs/sabenv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
>     app_config = AppConfig.create(entry)
>   File "/home/az/.virtualenvs/sabenv/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
>     module = import_module(entry)
>   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/az/.virtualenvs/sabenv/lib/python2.7/site-packages/autocomplete_light/__init__.py", line 7, in <module>
>     from .shortcuts import *  # noqa
>   File "/home/az/.virtualenvs/sabenv/lib/python2.7/site-packages/autocomplete_light/shortcuts.py", line 1, in <module>
>     from .autocomplete.shortcuts import *
>   File "/home/az/.virtualenvs/sabenv/lib/python2.7/site-packages/autocomplete_light/autocomplete/shortcuts.py", line 1, in <module>
>     from .base import AutocompleteBase
>   File "/home/az/.virtualenvs/sabenv/lib/python2.7/site-packages/autocomplete_light/autocomplete/base.py", line 4, in <module>
>     from django.urls import reverse, NoReverseMatch
> ImportError: No module named urls

May I ask, 
Are these the correct combination? Geonode 2.8rc11 , Cartoview 1.8.1, Django 1.8.19

**Comment by lolob** [comment]
Hi,
Again no luck here.

> (envsabah) az@ubuntusa:~/sabrs$ python manage.py makemigrations app_manager
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/az/.virtualenvs/envsab/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/home/az/.virtualenvs/envsab/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
>     django.setup()
>   File "/home/az/.virtualenvs/envsab/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/az/.virtualenvs/envsab/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
>     app_config = AppConfig.create(entry)
>   File "/home/az/.virtualenvs/envsab/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
>     module = import_module(entry)
>   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/az/.virtualenvs/envsab/lib/python2.7/site-packages/polymorphic/__init__.py", line 13, in <module>
>     __version__ = pkg_resources.require("django-polymorphic")[0].version
>   File "/home/az/.virtualenvs/envsab/lib/python2.7/site-packages/pkg_resources/__init__.py", line 891, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/home/az/.virtualenvs/envsab/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (Django 1.8.19 (/home/az/.virtualenvs/envsab/lib/python2.7/site-packages), Requirement.parse('Django>=1.11'), set(['django-polymorphic']))

Below is the list of in my requirements.txt

```
amqp==1.4.9
anyjson==0.3.3
awesome-slugify==1.6.5
beautifulsoup4==4.6.0
billiard==3.3.0.23
boto==2.49.0
cartoview==1.8.1
celery==3.1.26.post2
certifi==2018.4.16
chardet==3.0.4
configparser==3.5.0
dj-database-url==0.5.0
Django==1.8.19
django-activity-stream==0.6.5
django-appconf==1.0.2
django-autocomplete-light==2.3.3
django-bootstrap-form==3.4
django-bootstrap3-datetimepicker==2.2.3
django-braces==1.13.0
django-braces==1.13.0
django-celery==3.2.2
django-downloadview==1.9
django-extensions==2.1.0
django-forms-bootstrap==3.1.0
django-friendly-tag-loader==1.3
django-geoexplorer==4.0.40
django-guardian==1.4.9
django-haystack==2.8.1
django-js-asset==1.1.0
django-jsonfield==1.0.1
django-jsonfield-compat==0.4.4
django-leaflet==0.24.0
django-modeltranslation==0.12.2
django-mptt==0.9.0
django-nose==1.4.5
django-oauth-toolkit==0.12.0
django-pagination==1.0.7
django-polymorphic==2.0.2
django-storages==1.6.6
django-taggit==0.22.2
django-tastypie==0.13.1
django-treebeard==4.3
elasticsearch==6.3.0
enum34==1.1.6
flake8==3.5.0
future==0.16.0
GDAL==2.2.2
geolinks==0.2.0
GeoNode==2.6.3
geonode-agon-ratings==0.3.8
geonode-announcements==1.0.13
geonode-arcrest==10.2
geonode-avatar==2.1.8
geonode-dialogos==1.2
geonode-notification==1.1.3
geonode-user-accounts==1.0.15
geonode-user-messages==0.1.14
gisdata==0.5.4
gsconfig==1.0.10
gsimporter==1.0.0
httplib2==0.11.3
idna==2.7
kombu==3.0.37
lxml==4.2.3
mccabe==0.6.1
MultipartPostHandler==0.1.0
nose==1.3.7
oauthlib==2.0.1
OWSLib==0.16.0
Paver==1.3.4
pep8==1.7.1
Pillow==5.2.0
pinax-theme-bootstrap==8.0.1
pinax-theme-bootstrap-account==1.0b2
psycopg2==2.7.5
pycodestyle==2.3.1
pycsw==2.2.0
pyelasticsearch==1.4.1
pyflakes==1.6.0
pyproj==1.9.5.1
python-dateutil==2.7.3
python-mimeparse==1.6.0
python-slugify==1.2.5
pytz==2018.5
PyYAML==3.13
regex==2018.7.11
requests==2.19.1
Shapely==1.5.17
simplejson==3.16.0
six==1.10.0
transifex-client==0.13.4
typing==3.6.4
Unidecode==0.4.21
urllib3==1.23
xmltodict==0.10.2
```
Please advise. Thanks.

**Comment by ahmednoureldeen** [comment]
I see that `GeoNode==2.6.3` in requirement.txt , which branch did you install ??

**Comment by lolob** [comment]
Actually I'm trying to get the latest Cartoview==1.8.1 get to work but failed. My combination is Cartoview==1.8.1 , GeoNode==2.6.3, Django==1.8.19, Python==2.7.12
At the moment, I use the older version of Cartoview==1.2.55. And I want to test the latest.
If I want to use the latest version of Cartoview, what is the requirements to install and run.
Could you share your own `pip freeze > requirements.txt` . I would like to compare with mine.

**Comment by ahmednoureldeen** [comment]
here your are [requirements.txt](https://github.com/cartologic/cartoview/files/2227086/requirements.txt).

N.B.  cartoview 1.8.1 is note compatible with geonode 2.6.x .

**Comment by lolob** [comment]
Many thanks.
I made comparison and use some of the list based on your 'requirement.txt'. It wasn't smooth but manages to install. However I got some of the following during pip install:

```
pycsw 2.0.3 has requirement lxml==3.6.2, but you'll have lxml 3.8.0 which is incompatible.
pycsw 2.0.3 has requirement OWSLib==0.10.3, but you'll have owslib 0.15.0 which is incompatible.
pycsw 2.0.3 has requirement pyproj==1.9.3, but you'll have pyproj 1.9.5.1 which is incompatible.
pycsw 2.0.3 has requirement Shapely==1.3.1, but you'll have shapely 1.5.17 which is incompatible.
pinax-theme-bootstrap-account 1.0b2 has requirement django-appconf==0.5, but you'll have django-appconf 1.0.2 which is incompatible.
geonode 2.6.3 has requirement celery<4.0a0,>=3.1.18, but you'll have celery 4.1.0 which is incompatible.
geonode 2.6.3 has requirement django-tastypie<=0.13.1,>=0.12.2, but you'll have django-tastypie 0.14.0 which is incompatible.
django-haystack 2.8.0 has requirement Django>=1.11, but you'll have django 1.8.19 which is incompatible.
django-celery 3.2.2 has requirement celery<4.0,>=3.1.15, but you'll have celery 4.1.0 which is incompatible.
docker 3.1.1 has requirement requests!=2.18.0,>=2.14.2, but you'll have requests 2.11.1 which is incompatible.
flake8 2.5.4 has requirement pyflakes<1.1,>=0.8.1, but you'll have pyflakes 1.6.0 which is incompatible.
```
Like I said before, probably warning. I proceed until `python manage.py migrate account` and I got this:

> django.db.utils.OperationalError: no such table: django_site

I just re-run again couple times and it's gone. Then I proceed until `python manage.py runserver 192.168.1.10:8000` and I got this:

> File "/home/az/.virtualenvs/sabenv4/lib/python2.7/site-packages/cartoview/cartoview_api/rest.py", line 13, in <module>
>     from geonode.api.authorization import (
> ImportError: cannot import name GeonodeApiKeyAuthentication

I have know idea what to do next. Should I just comment out the code in the file or I think just wait from your advise.

**Comment by hishamkaram** [comment]
@killertonez which version of geonode you are using?

**Comment by hishamkaram** [comment]
@killertonez closed due to lack of response , feel free to reopen this issue again
