### ISSUE TITLE
Incompatible Apps in Cartoview 1.8.1

### ISSUE THREAD

**Issue by dpadron** [cartologic/cartoview#158]
Hello
I managed to install geonode 2.8rc11 + cartoview 1.8.1 + geoserver 2.12 on Ubuntu 16.04 in a clean installation.
But some Apps were not installed as WebApp Builder or Cartoview TerriaMap Viewer (Incompatible)
What could be the problem?

![image](https://user-images.githubusercontent.com/7094961/40982244-0a00c352-68dd-11e8-8936-0a71c75d8edb.png)

**Comment by dpadron** [comment]
Hi Hisham
Works correctly Thank you

**Comment by ahmednosman** [comment]
Dear @HKejo we do not have current plans to further support the web app builder for future releases. we expect that most functionality in the web app builder will be further delivered from the basic viewer
ArcGIS fearture server will be available starting with the CartoView 1.10 coming out soon and will not be available for 1.8
