### ISSUE TITLE
Problem Install Cartoview

### ISSUE THREAD

**Issue by izelvor** [cartologic/cartoview#16]
Hello,
I would like to install Cartoview on my computer (Geonode 2.5.15+ Django 1.8.17 + Python2.7) in Ubuntu 14.04
I try to install Geonode 2.5.15 with :
   sudo add-apt-repository ppa:geonode/release
   sudo apt-get update
   sudo apt-get install geonode
But it's not working.
Could you help me please ?

**Comment by hishamkaram** [comment]
Hello @izelvor 
please install geonode with this command `pip install geonode`
and follow the steps [here](http://cartologic.github.io/installation/) 
or by using docker from [here](http://cartologic.github.io/docker/)

**Comment by izelvor** [comment]
Hello,
Thank you for your answer but I can not install cartoview.
Here are the commands I used to try to install geonode. Can you tell me what I did wrong and why I can not install the software, please?
- Python 2.7:
     sudo apt-get install build-essential checkinstall
     sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
     cd /usr/src
     wget https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tgz
     tar xzf Python-2.7.13.tgz
     cd Python-2.7.13
     sudo ./configure
     sudo make altinstall
- pip-python
     sudo apt-get update
     sudo apt-get upgrade
     apt-get -y install python-pip
- Django 1.8.17
     pip install django==1.8.17
- geonode 2.5.15
     pip install geonode

I have this error :
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/psycopg2
Storing debug log for failure in /home/izelvor/.pip/pip.log

What I have to do to finalize the installation without error ?

**Comment by hishamkaram** [comment]
you need to install some libraries with this command
`sudo apt-get install python-virtualenv python-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev libpq-dev libgdal-dev git default-jdk`

**Comment by izelvor** [comment]
Thank you very much, I was able to install geonode with your command line.
But I wanted to continue the installation of cartoview by following the instructions in [this link](http://cartologic.github.io/installation/).
- pip install cartoview -> ok
 - django-admin.py startproject --template=https://github.com/cartologic/cartoview-project-template/archive/master.zip --name django.env,uwsgi.ini,.bowerrc cartoweb -> ok
- cd cartoweb -> ok
- python manage.py makemigrations app_manager
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/geonode/base/models.py", line 56, in <module>
    from geonode.utils import bbox_to_wkt
  File "/usr/local/lib/python2.7/dist-packages/geonode/utils.py", line 30, in <module>
    from osgeo import ogr
ImportError: No module named osgeo

I would like to know if it's correct this error and if I can continue with the next command : python manage.py migrate people

Thank you in advance for your help

**Comment by izelvor** [comment]
Hello,
I installed Geonode 2.5.15 on ubuntu 14.04.
Everything seemed to be okay, but, when I try to UPLOAD a GeoTIFF or a Shape File on the Geonode Website, I'm getting the following error message: 
"[Errno 111] Connection refused". Has anyone ever got an "Errno 111" on Geonode?
Sincerely,

**Comment by hishamkaram** [comment]
Configure Geoserver before uploading layers from [here](http://docs.geonode.org/en/master/tutorials/admin/geoserver_geonode_security/#geoserver-security-backend)

**Comment by izelvor** [comment]
What is the address to connect to geoserver? I tried with this address localhost:8080/geoserver, but the page does not exist and I can not connect. How do I know if geoserver has been installed? What is the python command to start geoserver?
Sincerly

**Comment by hishamkaram** [comment]
(option 1): in geonode folder type : paver `start_geoservre` 
(option 2):
install tomcat on ubuntu the download geoserver war file from [here](http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war) and rename downloaded file to `geoserver.war` and cp it to webapps folder in tomcat home

**Comment by izelvor** [comment]
Thank you,
Which version of tomcat should I install on ubuntu 14.04?
How to install tomcat and java 8 for geoserver 2.9?
Do I have to install after PostGIS?
Sincerly

**Comment by hishamkaram** [comment]
Use this [guide](
https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-ubuntu-16-04)
to install tomcat
And then follow step in my previous comment
The secend part of your question if you want to use cartoview you have to
install postgis if you are testing geonode only you don't need to install it

**Comment by izelvor** [comment]
Hello,
I have installed tomcat 8 with java 8. I must now test the application to see if everything is properly installed.
Which version of postgresql / postgis should I install for the next step?
Looking at this [page](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/install_geonode_application.html), there are different packages to install? Do I have to install other packages from this list?
Thank you again for your help.

**Comment by hishamkaram** [comment]
- postgres 9.5 , postgis 2.2 required 
- for ubuntu 16.04 you can install these packages to compile required python libraries using this command
`sudo apt-get install python-virtualenv python-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev libpq-dev libgdal-dev git default-jdk python-gdal -y`
 
note : you can find required packages in our docker file(cartoview docker image based on ubuntu 16.04 so you can install the same packages) from [here](https://github.com/cartologic/cartoview-docker/blob/master/Dockerfile)

**Comment by izelvor** [comment]
Thank you for your reply.
I will try with Ubuntu 16.04
Sincerly

**Comment by hishamkaram** [comment]
you can continue with ubuntu 14.04 
for ubuntu 1404 you can install these packages to compile required python libraries using this command
- ```sudo apt-get install python-virtualenv python-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev libpq-dev libgdal-dev git default-jdk  -y```
- ```pip install pygdal==1.10.1```

**Comment by izelvor** [comment]
* I use virtualbox to run ubuntu. Do I have to install other software or libraries?

* I tried to install geonode with docker but for the function make static_db, I had this error:
docker-compose exec cartoview bower install --allow-root
bower                            retry Request to https://bower.herokuapp.com/packages/angular-messages failed with ETIMEDOUT, retrying in 1.1s
bower                            retry Request to https://bower.herokuapp.com/packages/angular-material failed with ETIMEDOUT, retrying in 1.8s
bower                            retry Request to https://bower.herokuapp.com/packages/angular-resource failed with ETIMEDOUT, retrying in 1.4s
bower                            retry Request to https://bower.herokuapp.com/packages/angular-resource-tastypie failed with ETIMEDOUT, retrying in 1.0s
bower                            retry Request to https://bower.herokuapp.com/packages/normalize-css failed with ETIMEDOUT, retrying in 1.7s
bower                            retry Request to https://bower.herokuapp.com/packages/angular-bootstrap failed with ETIMEDOUT, retrying in 1.3s
bower                            retry Request to https://bower.herokuapp.com/packages/angular-drag-and-drop-lists failed with ETIMEDOUT, retrying in 1.9s
bower                            retry Request to https://bower.herokuapp.com/packages/ng-image-appear failed with ETIMEDOUT, retrying in 1.4s
bower                            retry Request to https://bower.herokuapp.com/packages/lf-ng-md-file-input failed with ETIMEDOUT, retrying in 1.9s
bower                            retry Request to https://bower.herokuapp.com/packages/angular-img-fallback failed with ETIMEDOUT, retrying in 1.6s
bower angular#1.5.9          EAI_AGAIN Request to https://bower.herokuapp.com/packages/angular failed: getaddrinfo EAI_AGAIN bower.herokuapp.com:443
Makefile:28 : la recette pour la cible « bower » a échouée
make: *** [bower] Erreur 1

What do I need to finalize the installation, please ?
Sincerly

**Comment by NicholasDsouza1996** [comment]
![img-20170827-wa0007](https://user-images.githubusercontent.com/20857536/29748766-78ed4dc6-8b0c-11e7-9031-7ab70540d1c4.jpg)

Please can u help me with this error

**Comment by hishamkaram** [comment]
please install latest version of cartoview using this command:
`pip install cartoview -U --no-cache-dir `

**Comment by NicholasDsouza1996** [comment]
![screenshot from 2017-08-27 15-21-08](https://user-images.githubusercontent.com/20857536/29748815-59733b12-8b0d-11e7-9146-08be4e4582

Just tried it but doesnt seem to work

**Comment by hishamkaram** [comment]
did you followed the steps in the [docs](http://cartologic.github.io) ??

**Comment by NicholasDsouza1996** [comment]
yes

**Comment by NicholasDsouza1996** [comment]
yes

**Comment by hishamkaram** [comment]
is this is your local machine or remote one?

**Comment by NicholasDsouza1996** [comment]
local machine

**Comment by hishamkaram** [comment]
ok please can you provide me with your `local_settings.py`

**Comment by hishamkaram** [comment]
and python version??

**Comment by NicholasDsouza1996** [comment]
please can u tell me where can i find local_settings.py file?

**Comment by NicholasDsouza1996** [comment]
Python version is 3.5.2

**Comment by hishamkaram** [comment]
okay we are using python 2.7

> Installation Requirements¶
> 
> Install Python2.7
> 
> Install Django
please read [the docs](http://cartologic.github.io/installation_ubuntu/) carefully
or use docker to avoid these errors

**Comment by NicholasDsouza1996** [comment]
i also have already installed python 2.7.12

**Comment by NicholasDsouza1996** [comment]
i also have already installed python 2.7.12

**Comment by hishamkaram** [comment]
please be sure with version you are using with cartoview , from screenshot  you are not using virtualenv for cartoview setup as in docs please don't skip any step

**Comment by NicholasDsouza1996** [comment]
ok thankyou. I just rechecked and i installed the virtualenv and stuff. Now the previous error which i got has vanished and ive got a more concise error

**Comment by NicholasDsouza1996** [comment]
![carto](https://user-images.githubusercontent.com/20857536/29749064-81a645a6-8b13-11e7-9d1e-64b2c2b0c9f1.png)

**Comment by NicholasDsouza1996** [comment]
Can someone please help me?

**Comment by hishamkaram** [comment]
please install geonode using this command:
`pip install geonode`

**Comment by NicholasDsouza1996** [comment]
Thankou very much for the help you have given me so far hishamkaram.

**Comment by hishamkaram** [comment]
you are welcome @NicholasDsouza1996

**Comment by NicholasDsouza1996** [comment]
can u please solve this problem

**Comment by hishamkaram** [comment]
install geonode package : it will solve the problem
`pip install geonode`

**Comment by NicholasDsouza1996** [comment]
Thankyou very much Hishamkaram looks like after reinstalling geonode and cartoview my problem is solved.

**Comment by NicholasDsouza1996** [comment]
I have a question i typed: python manage.py makemigrations app_manager

Output:
System check identified some issues:

WARNINGS:
base.ResourceBase.tkeywords: (fields.W340) null has no effect on ManyToManyField.
No changes detected in app 'app_manager'

What should i do?

**Comment by NicholasDsouza1996** [comment]
ive completed it. Thanks a ton.
