### ISSUE TITLE
Use https for App Store URL

### ISSUE THREAD

**Issue by davisc** [cartologic/cartoview#160]
https://github.com/cartologic/cartoview/blob/0d3ee0f8598574baedec1f1582557ce7eb2d9224/cartoview/app_manager/fixtures/app_stores.json#L1

To avoid mix-content errors for ssl enabled deployments, can the App Store URL be changed to https://appstore.cartoview.net/api/v1/ rather than http://?

**Comment by ahmednoureldeen** [comment]
fixed
