### ISSUE TITLE
Install with existing geonode

### ISSUE THREAD

**Issue by killertonez** [cartologic/cartoview#169]
## Please fill the following information to avoid closing issue

Unable to install Cartoview to existing geonode

- Cartoview Version : (1.8.2rc4)
- Geonode Version : (2.8)
- log (optional):
```
  File "/usr/local/lib/python2.7/dist-packages/geonode/settings.py", line 1331, in <module>
    from cartoview import settings as cartoview_settings
  File "/usr/local/lib/python2.7/dist-packages/cartoview/settings.py", line 29, in <module>
    execfile(cartoview_apps_settings_path)
  File "/usr/local/lib/python2.7/dist-packages/cartoview/app_manager/settings.py", line 20, in <module>
    APPS_DIR = os.path.abspath(os.path.join(BASE_DIR, "apps"))
NameError: name 'BASE_DIR' is not defined

```

**Comment by hishamkaram** [comment]
Hello killertonez
Try to replace BASE_DIR with PROJECT_ROOT

**Comment by killertonez** [comment]
Thank you so much, 

now i got past that part but now i get this error

  TEMPLATES[0]["OPTIONS"]['context_processors'] += cartoview_settings.CARTOVIE        W_CONTEXT_PROCESSORS
AttributeError: 'module' object has no attribute 'CARTOVIEW_CONTEXT_PROCESSORS'

**Comment by hishamkaram** [comment]
The instructions on github for the next cartoview version you can install
this version with pip install cartoview==1.8.2rc4

**Comment by killertonez** [comment]
ok i install 1.8.2 but now when adding to the settings and the code to the end of the file i get this error

  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named notifications

**Comment by hishamkaram** [comment]
@killertonez  this error related to geonode try to create clean virtualenv

**Comment by hishamkaram** [comment]
@killertonez closed due to lake of response, feel free to reopen this issue again
