### ISSUE TITLE
Incompatible Apps in Cartoview (CentOS 7)

### ISSUE THREAD

**Issue by fasingagerda** [cartologic/cartoview#176]
Hello

I manage to install geonode 2.8.0 and geoserver 2.12 in clean virtual env (myhome/myserver/.venvs/geonode)
Succeed in installation of  cartoview using pip  install cartoview==1.8.2 in the same virtual env with these step
1. (geonode)[myhome@myserver geonode]:$ pip install cartoview==1.8.2 --no-cache-dir
2. Add line in geonode setting.py by following https://github.com/cartologic/cartoview#how-to-add-cartoview-to-existing-geonode

>from cartoview import settings as cartoview_settings
>
>INSTALLED_APPS = cartoview_settings.INSTALLED_APPS
>ROOT_URLCONF = cartoview_settings.ROOT_URLCONF
>
>APPS_DIR = os.path.abspath(os.path.join(PROJECT_ROOT, "apps"))
>PENDING_APPS = os.path.join(PROJECT_ROOT, "pendingOperation.yml")
>
>TEMPLATES[0]["DIRS"] = cartoview_settings.CARTOVIEW_TEMPLATE_DIRS + TEMPLATES[0]["DIRS"]
>TEMPLATES[0]["OPTIONS"]['context_processors'] += cartoview_settings.CARTOVIEW_CONTEXT_PROCESSORS
>
>STATICFILES_DIRS += cartoview_settings.CARTOVIEW_STATIC_DIRS
>
>from cartoview.app_manager.settings import load_apps
>INSTALLED_APPS += load_apps()

3. run python manage.py migrate
4. run python manage.py loaddata geonode/base/fixtures/initial_data.json
5. run python manage.py loaddata app_store.json
6. run python manage.py collectstatic
7. add appstore url in admin panel > app manager > apps store which refere to appstore.cartoview.net/api/v1

Both installation were successfull but problem occurs when I try to install apps where all the apps (in app manager) are in the status of incompatible and there are no active install button

![image](https://user-images.githubusercontent.com/36129747/44904305-1f9e2880-ad39-11e8-9260-d9726c7fe692.png)

What could be the problem?

- Cartoview Version : (1.8.2)
- Geonode Version : (2.8.0)

- log (optional):

**Comment by ahmednosman** [comment]
Hello
We are going through 15 apps batch now to test, will be released in less than 3 days
Apologies for the inconvenience

**Comment by fasingagerda** [comment]
ok i will wait for the test result then
thanx

**Comment by hishamkaram** [comment]
@fasingagerda @ahmednosman Basic Viewer is now available to install

**Comment by hishamkaram** [comment]
@fasingagerda 
sorry for being late 
- please upgrade to 1.8.3 using the following command:
`pip install cartoview==1.8.3 --no-cache-dir`
- now open` /apps/manage` you can find around 7 compatible  apps to install , we are working on 16 app to make them compatible

**Comment by fasingagerda** [comment]
@ahmednosman @hishamkaram 
thank you so much guys,
I try several apps that already compatible (tutorial and basic viewer) through app manager but the installation process keep running and not stopping, the server also not restarting as it should be
but when I check the apps folder i find that the apps are registered in apps.yml and the apps folders are being downloaded so what i am doing next is just manually fill the apps information in admin menu and the apps are now available in my geonode cartoview site 
I will try the other apps then
again thanx so much and still waiting for the others apps to become available in 1.8.3 version

**Comment by hishamkaram** [comment]
@fasingagerda  
- could you show me the content of apps.yml ?
- apps folder permissions (ls -al) ? 
- which server you are using (apache, nginx+uwsgi, nginx+gunicorn)?

**Comment by fasingagerda** [comment]
@hishamkaram 
sorry for the slow respond

file setting.py --> /home/pusdatin/geonode/geonode/setting.py

[settings.py.txt](https://github.com/cartologic/cartoview/files/2365275/settings.py.txt)

project structure
/home/pusdatin/geonode
├── docs
│   ├── i18n
│   │   ├── de
│   │   │   └── LC_MESSAGES
│   │   ├── el
│   │   │   └── LC_MESSAGES
│   │   ├── es
│   │   │   └── LC_MESSAGES
│   │   ├── fa
│   │   │   └── LC_MESSAGES
│   │   ├── fil
│   │   │   └── LC_MESSAGES
│   │   ├── fr
│   │   │   └── LC_MESSAGES
│   │   ├── id
│   │   │   └── LC_MESSAGES
│   │   ├── it
│   │   │   └── LC_MESSAGES
│   │   ├── ja
│   │   │   └── LC_MESSAGES
│   │   ├── ko
│   │   │   └── LC_MESSAGES
│   │   ├── pt
│   │   │   └── LC_MESSAGES
│   │   ├── ru
│   │   │   └── LC_MESSAGES
│   │   ├── scripts
│   │   ├── vi
│   │   │   └── LC_MESSAGES
│   │   └── zh
│   │       └── LC_MESSAGES
│   ├── img
│   ├── organizational
│   │   ├── contribute
│   │   │   └── img
│   │   └── img
│   ├── reference
│   │   ├── developers
│   │   └── img
│   └── tutorials
│       ├── admin
│       │   ├── admin_mgmt_commands
│       │   ├── admin_panel
│       │   │   └── img
│       │   ├── async_signals
│       │   ├── backup_restore
│       │   │   └── img
│       │   ├── csw_settings
│       │   ├── customize_lookfeel
│       │   │   ├── customize
│       │   │   └── img
│       │   ├── database_shards
│       │   │   └── img
│       │   ├── debug_geonode
│       │   │   └── img
│       │   ├── default_lang
│       │   ├── geoserver_geonode_security
│       │   │   └── img
│       │   ├── install
│       │   │   └── img
│       │   ├── ldap
│       │   ├── loading_data_into_geonode
│       │   │   └── img
│       │   ├── monitoring
│       │   │   └── img
│       │   ├── more_on_security_and_permissions
│       │   │   └── img
│       │   ├── s3_config
│       │   └── socialaccounts
│       │       └── img
│       ├── advanced
│       │   ├── adv_data_mgmt
│       │   │   ├── adding_data
│       │   │   │   └── img
│       │   │   ├── adv_raster
│       │   │   │   ├── advanced_gdal
│       │   │   │   │   └── img
│       │   │   │   └── img
│       │   │   ├── adv_vector
│       │   │   │   └── img
│       │   │   ├── img
│       │   │   └── pretty_maps
│       │   │       └── img
│       │   ├── geonode_production
│       │   │   ├── adv_gsconfig
│       │   │   │   ├── img
│       │   │   │   └── jmeter
│       │   │   │       └── img
│       │   │   └── img
│       │   └── geonode_settings
│       ├── devel
│       │   ├── devel_core
│       │   ├── devel_debug
│       │   │   └── img
│       │   ├── devel_env
│       │   ├── devel_intro
│       │   ├── django_overview
│       │   ├── envsetup
│       │   ├── geonode_apis
│       │   │   ├── geonode
│       │   │   ├── geoserver_rest
│       │   │   │   ├── examples
│       │   │   │   │   └── resources
│       │   │   │   │       └── shapefiles
│       │   │   │   ├── img
│       │   │   │   └── resources
│       │   │   └── importer
│       │   │       └── images
│       │   ├── geonode_testing
│       │   ├── projects
│       │   └── release
│       ├── install_and_admin
│       │   ├── geonode_install
│       │   │   └── img
│       │   ├── geonode_update
│       │   │   └── 26_to_27
│       │   │       └── img
│       │   ├── img
│       │   ├── linux_admin_intro
│       │   │   └── img
│       │   ├── running_docker
│       │   │   ├── img
│       │   │   └── resources
│       │   ├── setup_on_centos
│       │   │   └── resources
│       │   └── win_bin_install
│       │       └── img
│       ├── overview_and_ref
│       │   ├── introduction
│       │   │   └── img
│       │   ├── reference_doc
│       │   │   └── img
│       │   └── user_features
│       └── users
│           ├── accounts_and_users
│           │   └── img
│           ├── document_types
│           │   └── img
│           ├── edit_style
│           │   └── img
│           ├── managing_layers
│           │   └── img
│           ├── managing_maps
│           │   └── img
│           ├── searching
│           │   └── img
│           └── using_geonode_w_other_applications
│               └── img
├── geonode
│   ├── api
│   │   └── fixtures
│   ├── apps
│   │   ├── cartoview_basic_viewer
│   │   │   ├── static
│   │   │   │   └── cartoview_basic_viewer
│   │   │   │       ├── dist
│   │   │   │       ├── img
│   │   │   │       └── src
│   │   │   │           ├── components
│   │   │   │           │   ├── edit
│   │   │   │           │   └── view
│   │   │   │           ├── containers
│   │   │   │           └── css
│   │   │   ├── templates
│   │   │   │   ├── base
│   │   │   │   └── cartoview_basic_viewer
│   │   │   └── templatetags
│   │   ├── cartoview_categorized_styler
│   │   │   ├── static
│   │   │   │   └── cartoview_categorized_styler
│   │   │   │       ├── css
│   │   │   │       ├── dist
│   │   │   │       ├── images
│   │   │   │       ├── src
│   │   │   │       │   ├── components
│   │   │   │       │   │   ├── Classifier
│   │   │   │       │   │   ├── GeneralSymbolizer
│   │   │   │       │   │   ├── Legend
│   │   │   │       │   │   └── Symbolizer
│   │   │   │       │   ├── constants
│   │   │   │       │   ├── gs-client
│   │   │   │       │   ├── heatmap
│   │   │   │       │   ├── helpers
│   │   │   │       │   └── managers
│   │   │   │       └── test
│   │   │   └── templates
│   │   │       └── cartoview_categorized_styler
│   │   ├── cartoview_heatmap_styler
│   │   │   ├── static
│   │   │   │   └── cartoview_heatmap_styler
│   │   │   │       ├── css
│   │   │   │       ├── dist
│   │   │   │       ├── images
│   │   │   │       ├── src
│   │   │   │       │   ├── components
│   │   │   │       │   │   ├── Classifier
│   │   │   │       │   │   ├── GeneralSymbolizer
│   │   │   │       │   │   ├── Legend
│   │   │   │       │   │   └── Symbolizer
│   │   │   │       │   ├── constants
│   │   │   │       │   ├── gs-client
│   │   │   │       │   ├── heatmap
│   │   │   │       │   ├── helpers
│   │   │   │       │   └── managers
│   │   │   │       └── test
│   │   │   └── templates
│   │   │       └── cartoview_heatmap_styler
│   │   └── cartoview_tutorials
│   │       ├── migrations
│   │       ├── static
│   │       │   └── cartoview_tutorials
│   │       │       └── css
│   │       └── templates
│   │           └── cartoview_tutorials
│   ├── base
│   │   ├── fixtures
│   │   ├── management
│   │   │   └── commands
│   │   │       └── lib
│   │   ├── migrations
│   │   ├── templates
│   │   │   └── base
│   │   └── templatetags
│   ├── catalogue
│   │   ├── backends
│   │   └── templates
│   │       └── catalogue
│   ├── client
│   │   ├── templates
│   │   │   ├── geoext
│   │   │   │   ├── layers
│   │   │   │   └── maps
│   │   │   ├── leaflet
│   │   │   │   ├── layers
│   │   │   │   └── maps
│   │   │   └── ol
│   │   │       ├── layers
│   │   │       └── maps
│   │   └── templatetags
│   ├── contrib
│   │   ├── api_basemaps
│   │   │   └── templatetags
│   │   ├── createlayer
│   │   │   ├── management
│   │   │   │   └── commands
│   │   │   └── templates
│   │   │       └── createlayer
│   │   ├── datastore_shards
│   │   ├── dynamic
│   │   ├── exif
│   │   │   └── templates
│   │   │       └── exif
│   │   ├── favorite
│   │   │   └── templates
│   │   │       └── favorite
│   │   ├── geogig
│   │   │   ├── static
│   │   │   │   └── geogig
│   │   │   │       └── css
│   │   │   ├── templates
│   │   │   └── templatetags
│   │   ├── geosites
│   │   │   ├── fixtures
│   │   │   ├── management
│   │   │   │   └── commands
│   │   │   ├── site_template
│   │   │   │   ├── conf
│   │   │   │   ├── static
│   │   │   │   │   ├── css
│   │   │   │   │   ├── img
│   │   │   │   │   └── js
│   │   │   │   └── templates
│   │   │   ├── static
│   │   │   │   ├── css
│   │   │   │   ├── img
│   │   │   │   └── js
│   │   │   ├── templates
│   │   │   │   └── search
│   │   │   └── templatetags
│   │   ├── metadataxsl
│   │   │   ├── management
│   │   │   │   └── commands
│   │   │   └── static
│   │   │       └── metadataxsl
│   │   ├── monitoring
│   │   │   ├── fixtures
│   │   │   ├── frontend
│   │   │   │   ├── bin
│   │   │   │   └── src
│   │   │   │       ├── components
│   │   │   │       │   ├── atoms
│   │   │   │       │   │   ├── hover-paper
│   │   │   │       │   │   ├── hr
│   │   │   │       │   │   └── map
│   │   │   │       │   ├── cels
│   │   │   │       │   │   ├── alert
│   │   │   │       │   │   ├── alerts
│   │   │   │       │   │   ├── cpu
│   │   │   │       │   │   ├── errors
│   │   │   │       │   │   ├── errors-rate
│   │   │   │       │   │   ├── frequent-layers
│   │   │   │       │   │   ├── geonode-data
│   │   │   │       │   │   ├── geonode-status
│   │   │   │       │   │   │   └── actions
│   │   │   │       │   │   ├── geoserver-status
│   │   │   │       │   │   │   └── actions
│   │   │   │       │   │   ├── health-check
│   │   │   │       │   │   ├── layer-select
│   │   │   │       │   │   ├── memory
│   │   │   │       │   │   ├── response-table
│   │   │   │       │   │   ├── response-time
│   │   │   │       │   │   ├── table-row
│   │   │   │       │   │   ├── throughput
│   │   │   │       │   │   ├── uptime
│   │   │   │       │   │   └── ws-data
│   │   │   │       │   ├── molecules
│   │   │   │       │   │   ├── average-cpu
│   │   │   │       │   │   ├── average-memory
│   │   │   │       │   │   ├── average-response-time
│   │   │   │       │   │   ├── max-response-time
│   │   │   │       │   │   ├── total-requests
│   │   │   │       │   │   └── ws-service-select
│   │   │   │       │   │       └── actions
│   │   │   │       │   └── organisms
│   │   │   │       │       ├── alert-list
│   │   │   │       │       ├── alert-setting
│   │   │   │       │       ├── error-detail
│   │   │   │       │       ├── error-list
│   │   │   │       │       ├── geonode-analytics
│   │   │   │       │       │   └── actions
│   │   │   │       │       ├── geonode-layers-analytics
│   │   │   │       │       │   └── actions
│   │   │   │       │       ├── geonode-status
│   │   │   │       │       │   └── actions
│   │   │   │       │       ├── geoserver-status
│   │   │   │       │       │   └── actions
│   │   │   │       │       ├── hardware-performance
│   │   │   │       │       ├── header
│   │   │   │       │       ├── most-active-ips
│   │   │   │       │       ├── software-performance
│   │   │   │       │       ├── stats
│   │   │   │       │       ├── ws-analytics
│   │   │   │       │       │   └── actions
│   │   │   │       │       └── ws-layers-analytics
│   │   │   │       │           └── actions
│   │   │   │       ├── containers
│   │   │   │       │   └── app
│   │   │   │       ├── fonts
│   │   │   │       ├── pages
│   │   │   │       │   ├── alert-config
│   │   │   │       │   │   └── actions
│   │   │   │       │   ├── alerts
│   │   │   │       │   ├── alerts-settings
│   │   │   │       │   ├── error-details
│   │   │   │       │   ├── errors
│   │   │   │       │   ├── hardware-performance
│   │   │   │       │   ├── home
│   │   │   │       │   └── software-performance
│   │   │   │       └── store
│   │   │   ├── management
│   │   │   │   └── commands
│   │   │   ├── migrations
│   │   │   ├── resources
│   │   │   ├── static
│   │   │   │   └── monitoring
│   │   │   └── templates
│   │   │       ├── monitoring
│   │   │       └── pinax
│   │   │           └── notifications
│   │   │               └── monitoring_alert
│   │   ├── mp
│   │   │   └── migrations
│   │   ├── nlp
│   │   ├── ows_api
│   │   └── slack
│   ├── documents
│   │   ├── management
│   │   │   └── commands
│   │   ├── migrations
│   │   ├── static
│   │   │   └── documents
│   │   └── templates
│   │       ├── documents
│   │       └── layouts
│   ├── geoserver
│   │   ├── management
│   │   │   └── commands
│   │   └── templates
│   │       └── geoserver
│   ├── groups
│   │   ├── fixtures
│   │   ├── migrations
│   │   ├── templates
│   │   │   └── groups
│   │   └── templatetags
│   ├── invitations
│   │   └── migrations
│   ├── layers
│   │   ├── fixtures
│   │   ├── management
│   │   │   └── commands
│   │   ├── migrations
│   │   ├── templates
│   │   │   ├── layers
│   │   │   ├── layouts
│   │   │   └── upload
│   │   └── templatetags
│   ├── locale
│   │   ├── af
│   │   │   └── LC_MESSAGES
│   │   ├── al
│   │   │   └── LC_MESSAGES
│   │   ├── am
│   │   │   └── LC_MESSAGES
│   │   ├── ar
│   │   │   └── LC_MESSAGES
│   │   ├── bg_BG
│   │   │   └── LC_MESSAGES
│   │   ├── bn
│   │   │   └── LC_MESSAGES
│   │   ├── de
│   │   │   └── LC_MESSAGES
│   │   ├── el
│   │   │   └── LC_MESSAGES
│   │   ├── en
│   │   │   └── LC_MESSAGES
│   │   ├── es
│   │   │   └── LC_MESSAGES
│   │   ├── fa
│   │   │   └── LC_MESSAGES
│   │   ├── fa_IR
│   │   │   └── LC_MESSAGES
│   │   ├── fi
│   │   │   └── LC_MESSAGES
│   │   ├── fil
│   │   │   └── LC_MESSAGES
│   │   ├── fr
│   │   │   └── LC_MESSAGES
│   │   ├── hu
│   │   │   └── LC_MESSAGES
│   │   ├── id
│   │   │   └── LC_MESSAGES
│   │   ├── it
│   │   │   └── LC_MESSAGES
│   │   ├── ja
│   │   │   └── LC_MESSAGES
│   │   ├── ka
│   │   │   └── LC_MESSAGES
│   │   ├── km
│   │   │   └── LC_MESSAGES
│   │   ├── ko
│   │   │   └── LC_MESSAGES
│   │   ├── lt
│   │   │   └── LC_MESSAGES
│   │   ├── ne
│   │   │   └── LC_MESSAGES
│   │   ├── nl_NL
│   │   │   └── LC_MESSAGES
│   │   ├── no
│   │   │   └── LC_MESSAGES
│   │   ├── pl
│   │   │   └── LC_MESSAGES
│   │   ├── pt
│   │   │   └── LC_MESSAGES
│   │   ├── pt_BR
│   │   │   └── LC_MESSAGES
│   │   ├── ro
│   │   │   └── LC_MESSAGES
│   │   ├── ru
│   │   │   └── LC_MESSAGES
│   │   ├── si
│   │   │   └── LC_MESSAGES
│   │   ├── sq
│   │   │   └── LC_MESSAGES
│   │   ├── sv
│   │   │   └── LC_MESSAGES
│   │   ├── sw
│   │   │   └── LC_MESSAGES
│   │   ├── ta
│   │   │   └── LC_MESSAGES
│   │   ├── th
│   │   │   └── LC_MESSAGES
│   │   ├── tl
│   │   │   └── LC_MESSAGES
│   │   ├── uk
│   │   │   └── LC_MESSAGES
│   │   ├── vi
│   │   │   └── LC_MESSAGES
│   │   └── zh
│   │       └── LC_MESSAGES
│   ├── maps
│   │   ├── management
│   │   │   └── commands
│   │   ├── migrations
│   │   └── templates
│   │       ├── layouts
│   │       └── maps
│   ├── messaging
│   │   └── management
│   │       └── commands
│   ├── people
│   │   ├── fixtures
│   │   ├── migrations
│   │   ├── static
│   │   │   └── people
│   │   │       └── img
│   │   ├── templates
│   │   │   └── people
│   │   └── templatetags
│   ├── proxy
│   ├── qgis_server
│   │   ├── management
│   │   │   └── commands
│   │   ├── migrations
│   │   ├── tasks
│   │   ├── templates
│   │   │   └── qgis_server
│   │   │       └── forms
│   │   └── tests
│   │       └── data
│   ├── security
│   │   └── fixtures
│   ├── services
│   │   ├── management
│   │   │   └── commands
│   │   ├── migrations
│   │   ├── serviceprocessors
│   │   └── templates
│   │       └── services
│   ├── social
│   │   ├── templates
│   │   │   └── social
│   │   └── templatetags
│   ├── static
│   │   ├── geonode
│   │   │   ├── css
│   │   │   │   └── geoexplorer
│   │   │   ├── fonts
│   │   │   ├── img
│   │   │   ├── js
│   │   │   │   ├── base
│   │   │   │   ├── extjs
│   │   │   │   ├── search
│   │   │   │   ├── status
│   │   │   │   ├── templates
│   │   │   │   ├── tests
│   │   │   │   ├── upload
│   │   │   │   └── utils
│   │   │   └── less
│   │   │       └── bootstrap
│   │   │           └── mixins
│   │   └── lib
│   │       ├── css
│   │       ├── img
│   │       └── js
│   ├── static_root
│   │   ├── admin
│   │   │   ├── css
│   │   │   ├── fonts
│   │   │   ├── img
│   │   │   │   └── gis
│   │   │   └── js
│   │   │       ├── admin
│   │   │       └── vendor
│   │   │           ├── jquery
│   │   │           └── xregexp
│   │   ├── agon_ratings
│   │   │   ├── img
│   │   │   └── js
│   │   ├── app_manager
│   │   │   ├── bootstrap-sortable
│   │   │   │   ├── css
│   │   │   │   └── js
│   │   │   ├── css
│   │   │   ├── images
│   │   │   ├── img
│   │   │   ├── js
│   │   │   └── vendor
│   │   │       ├── angular
│   │   │       ├── angular-aria
│   │   │       ├── angular-bootstrap
│   │   │       ├── angular-drag-and-drop-lists
│   │   │       ├── angular-img-fallback
│   │   │       └── angular-resource
│   │   ├── autocomplete_light
│   │   ├── bootstrap-3-arabic
│   │   │   ├── css
│   │   │   ├── fonts
│   │   │   └── js
│   │   ├── cartoview
│   │   │   ├── css
│   │   │   ├── img
│   │   │   ├── js
│   │   │   │   └── appinstance
│   │   │   └── slider
│   │   │       ├── dist
│   │   │       └── src
│   │   ├── cartoview_basic_viewer
│   │   │   ├── dist
│   │   │   ├── img
│   │   │   └── src
│   │   │       ├── components
│   │   │       │   ├── edit
│   │   │       │   └── view
│   │   │       ├── containers
│   │   │       └── css
│   │   ├── cartoview_categorized_styler
│   │   │   ├── css
│   │   │   ├── dist
│   │   │   ├── images
│   │   │   ├── src
│   │   │   │   ├── components
│   │   │   │   │   ├── Classifier
│   │   │   │   │   ├── GeneralSymbolizer
│   │   │   │   │   ├── Legend
│   │   │   │   │   └── Symbolizer
│   │   │   │   ├── constants
│   │   │   │   ├── gs-client
│   │   │   │   ├── heatmap
│   │   │   │   ├── helpers
│   │   │   │   └── managers
│   │   │   └── test
│   │   ├── cartoview_heatmap_styler
│   │   │   ├── css
│   │   │   ├── dist
│   │   │   ├── images
│   │   │   ├── src
│   │   │   │   ├── components
│   │   │   │   │   ├── Classifier
│   │   │   │   │   ├── GeneralSymbolizer
│   │   │   │   │   ├── Legend
│   │   │   │   │   └── Symbolizer
│   │   │   │   ├── constants
│   │   │   │   ├── gs-client
│   │   │   │   ├── heatmap
│   │   │   │   ├── helpers
│   │   │   │   └── managers
│   │   │   └── test
│   │   ├── cartoview_tutorials
│   │   │   └── css
│   │   ├── compare-versions
│   │   ├── django_extensions
│   │   │   ├── css
│   │   │   ├── img
│   │   │   └── js
│   │   ├── documents
│   │   ├── floppyforms
│   │   │   ├── gis
│   │   │   │   └── img
│   │   │   ├── js
│   │   │   └── openlayers
│   │   │       └── theme
│   │   │           └── default
│   │   │               └── img
│   │   ├── geoexplorer
│   │   │   ├── externals
│   │   │   │   ├── ext
│   │   │   │   │   ├── adapter
│   │   │   │   │   │   ├── ext
│   │   │   │   │   │   ├── jquery
│   │   │   │   │   │   ├── prototype
│   │   │   │   │   │   └── yui
│   │   │   │   │   └── resources
│   │   │   │   │       ├── css
│   │   │   │   │       │   ├── structure
│   │   │   │   │       │   ├── theme-access
│   │   │   │   │       │   ├── theme-gray
│   │   │   │   │       │   └── visual
│   │   │   │   │       └── images
│   │   │   │   │           ├── access
│   │   │   │   │           │   ├── box
│   │   │   │   │           │   ├── button
│   │   │   │   │           │   ├── editor
│   │   │   │   │           │   ├── form
│   │   │   │   │           │   ├── grid
│   │   │   │   │           │   ├── menu
│   │   │   │   │           │   ├── panel
│   │   │   │   │           │   ├── progress
│   │   │   │   │           │   ├── qtip
│   │   │   │   │           │   ├── shared
│   │   │   │   │           │   ├── sizer
│   │   │   │   │           │   ├── slider
│   │   │   │   │           │   ├── tabs
│   │   │   │   │           │   ├── toolbar
│   │   │   │   │           │   ├── tree
│   │   │   │   │           │   └── window
│   │   │   │   │           ├── default
│   │   │   │   │           │   ├── box
│   │   │   │   │           │   ├── button
│   │   │   │   │           │   ├── dd
│   │   │   │   │           │   ├── editor
│   │   │   │   │           │   ├── form
│   │   │   │   │           │   ├── grid
│   │   │   │   │           │   ├── layout
│   │   │   │   │           │   ├── menu
│   │   │   │   │           │   ├── panel
│   │   │   │   │           │   ├── progress
│   │   │   │   │           │   ├── qtip
│   │   │   │   │           │   ├── shared
│   │   │   │   │           │   ├── sizer
│   │   │   │   │           │   ├── slider
│   │   │   │   │           │   ├── tabs
│   │   │   │   │           │   ├── toolbar
│   │   │   │   │           │   ├── tree
│   │   │   │   │           │   └── window
│   │   │   │   │           ├── gray
│   │   │   │   │           │   ├── button
│   │   │   │   │           │   ├── form
│   │   │   │   │           │   ├── grid
│   │   │   │   │           │   ├── menu
│   │   │   │   │           │   ├── panel
│   │   │   │   │           │   ├── progress
│   │   │   │   │           │   ├── qtip
│   │   │   │   │           │   ├── shared
│   │   │   │   │           │   ├── sizer
│   │   │   │   │           │   ├── slider
│   │   │   │   │           │   ├── tabs
│   │   │   │   │           │   ├── toolbar
│   │   │   │   │           │   ├── tree
│   │   │   │   │           │   └── window
│   │   │   │   │           ├── vista
│   │   │   │   │           │   ├── basic-dialog
│   │   │   │   │           │   ├── grid
│   │   │   │   │           │   ├── layout
│   │   │   │   │           │   ├── qtip
│   │   │   │   │           │   ├── sizer
│   │   │   │   │           │   ├── tabs
│   │   │   │   │           │   └── toolbar
│   │   │   │   │           └── yourtheme
│   │   │   │   │               ├── box
│   │   │   │   │               ├── button
│   │   │   │   │               ├── dd
│   │   │   │   │               ├── editor
│   │   │   │   │               ├── form
│   │   │   │   │               ├── grid
│   │   │   │   │               ├── layout
│   │   │   │   │               ├── menu
│   │   │   │   │               ├── panel
│   │   │   │   │               ├── progress
│   │   │   │   │               ├── qtip
│   │   │   │   │               ├── shared
│   │   │   │   │               ├── sizer
│   │   │   │   │               ├── slider
│   │   │   │   │               ├── tabs
│   │   │   │   │               ├── toolbar
│   │   │   │   │               ├── tree
│   │   │   │   │               └── window
│   │   │   │   ├── GeoExt
│   │   │   │   │   └── resources
│   │   │   │   │       ├── css
│   │   │   │   │       └── images
│   │   │   │   │           ├── default
│   │   │   │   │           └── gray
│   │   │   │   ├── gxp
│   │   │   │   │   └── src
│   │   │   │   │       └── theme
│   │   │   │   │           └── img
│   │   │   │   │               ├── geosilk
│   │   │   │   │               ├── silk
│   │   │   │   │               └── thumbs
│   │   │   │   │                   └── mapbox
│   │   │   │   ├── openlayers
│   │   │   │   │   └── theme
│   │   │   │   │       └── default
│   │   │   │   │           └── img
│   │   │   │   └── PrintPreview
│   │   │   │       └── resources
│   │   │   │           ├── css
│   │   │   │           └── images
│   │   │   │               └── silk
│   │   │   ├── script
│   │   │   └── theme
│   │   │       ├── app
│   │   │       │   └── img
│   │   │       │       ├── geosilk
│   │   │       │       └── silk
│   │   │       └── ux
│   │   │           ├── colorpicker
│   │   │           ├── css
│   │   │           └── images
│   │   ├── geonode
│   │   │   ├── css
│   │   │   │   └── geoexplorer
│   │   │   ├── fonts
│   │   │   ├── img
│   │   │   ├── js
│   │   │   │   ├── base
│   │   │   │   ├── extjs
│   │   │   │   ├── search
│   │   │   │   ├── status
│   │   │   │   ├── templates
│   │   │   │   ├── tests
│   │   │   │   ├── upload
│   │   │   │   └── utils
│   │   │   └── less
│   │   │       └── bootstrap
│   │   │           └── mixins
│   │   ├── gis
│   │   │   └── js
│   │   ├── guardian
│   │   │   └── img
│   │   ├── leaflet
│   │   │   ├── draw
│   │   │   │   └── images
│   │   │   └── images
│   │   ├── lib
│   │   │   ├── css
│   │   │   ├── img
│   │   │   └── js
│   │   ├── metadataxsl
│   │   ├── modeltranslation
│   │   │   ├── css
│   │   │   └── js
│   │   ├── monitoring
│   │   ├── mptt
│   │   ├── people
│   │   │   └── img
│   │   ├── pinax
│   │   │   ├── css
│   │   │   └── js
│   │   ├── polymorphic
│   │   │   ├── css
│   │   │   └── js
│   │   └── treebeard
│   ├── tasks
│   ├── templates
│   │   ├── account
│   │   │   ├── email
│   │   │   └── snippets
│   │   ├── actstream
│   │   ├── admin
│   │   │   └── backups
│   │   ├── announcements
│   │   ├── avatar
│   │   ├── dialogos
│   │   ├── invitations
│   │   │   ├── email
│   │   │   └── forms
│   │   ├── pinax
│   │   │   └── notifications
│   │   │       ├── account_active
│   │   │       ├── account_approve
│   │   │       ├── document_approved
│   │   │       ├── document_comment
│   │   │       ├── document_created
│   │   │       ├── document_deleted
│   │   │       ├── document_published
│   │   │       ├── document_rated
│   │   │       ├── document_updated
│   │   │       ├── layer_approved
│   │   │       ├── layer_comment
│   │   │       ├── layer_created
│   │   │       ├── layer_deleted
│   │   │       ├── layer_published
│   │   │       ├── layer_rated
│   │   │       ├── layer_updated
│   │   │       ├── map_approved
│   │   │       ├── map_comment
│   │   │       ├── map_created
│   │   │       ├── map_deleted
│   │   │       ├── map_published
│   │   │       ├── map_rated
│   │   │       ├── map_updated
│   │   │       └── request_download_resourcebase
│   │   ├── relationships
│   │   ├── search
│   │   │   └── indexes
│   │   │       ├── documents
│   │   │       ├── groups
│   │   │       ├── layers
│   │   │       ├── maps
│   │   │       └── people
│   │   ├── socialaccount
│   │   │   └── snippets
│   │   └── user_messages
│   ├── tests
│   │   └── bdd
│   │       ├── e2e
│   │       │   └── fixtures
│   │       └── features
│   ├── upload
│   │   ├── migrations
│   │   ├── templatetags
│   │   └── tests
│   └── uploaded
│       ├── layers
│       └── thumbs
├── GeoNode.egg-info
├── package
│   ├── debian
│   │   ├── source
│   │   └── support
│   ├── geoserver
│   │   ├── debian
│   │   └── rpm
│   │       └── SPECS
│   ├── opensuse
│   ├── osgeo
│   ├── rpm
│   │   └── SPECS
│   └── support
└── scripts
    ├── backup-restore
    ├── celery
    ├── cloud
    ├── docker
    │   └── env
    │       ├── development
    │       └── production
    ├── jenkins
    └── misc

911 directories

**Comment by hishamkaram** [comment]
@fasingagerda could you show me the content of the `settings.py` and `local_settings.py`

**Comment by hishamkaram** [comment]
@fasingagerda sorry for being late , I am going to check this

**Comment by fasingagerda** [comment]
hello @hishamkaram, are there any missconfiguration in setting.py and local_setting.py?

**Comment by hishamkaram** [comment]
@fasingagerda  sorry for being late could you clone cartoview from github and go to cloned folder and install cartoview using 
- `pip install -e .`

and in your settings.py replace old cartoview settings with the following:
```
from cartoview import settings as cartoview_settings

INSTALLED_APPS += cartoview_settings.CARTOVIEW_INSTALLED_APPS
ROOT_URLCONF = cartoview_settings.ROOT_URLCONF

APPS_DIR = os.path.abspath(os.path.join(PROJECT_ROOT, "apps"))
PENDING_APPS = os.path.join(PROJECT_ROOT, "pendingOperation.yml")
APPS_MENU=False
# NOTE: please comment the following line of you want to use geonode templates
TEMPLATES[0][
    "DIRS"] = cartoview_settings.CARTOVIEW_TEMPLATE_DIRS + TEMPLATES[0]["DIRS"]
TEMPLATES[0]["OPTIONS"][
    'context_processors'] += cartoview_settings.CARTOVIEW_CONTEXT_PROCESSORS

STATICFILES_DIRS += cartoview_settings.CARTOVIEW_STATIC_DIRS

from cartoview.app_manager.settings import load_apps
INSTALLED_APPS += load_apps(APPS_DIR)
```

**Comment by fasingagerda** [comment]
thanx @hishamkaram , I'm going to try it

**Comment by fasingagerda** [comment]
@hishamkaram
i tried steps u gave me and here are some results
1. right now i can install app through apps manager, but server auto-restart won't work (have to do it manually after committing python manage.py collectstatic)
2. installed apps are work perfectly fine
3. uninstall app from manager won't work, again have to do it manually from admin panel, erasing the app folder and cleaning apps.yaml
4. so far only few apps that can be downloaded (tutorial, basic viewer, heatmap styler, graduated thematic layer, categorized thematic layer, dashboard, summary viewer, featured list viewer, and cartoview workspace) and the others are still in incompatible status. Is there any plan to continue testing the other apps?

**Comment by hishamkaram** [comment]
@fasingagerda sorry for being late
thank you for reporting app uninstall issue
for incompatible apps, some of these apps will be retired and the rest of these apps will be updated soon

**Comment by hishamkaram** [comment]
@fasingagerda now you can uninstall apps from admin panel

**Comment by hishamkaram** [comment]
git pull and restart server

**Comment by hishamkaram** [comment]
also you can uninstall from manage page now

**Comment by fasingagerda** [comment]
git pull.. done
restart server.. done

**Comment by fasingagerda** [comment]
Thanx @hishamkaram @ahmednosman 
I'll close this issue
