### ISSUE TITLE
speperate use of GeoNode in Windows

### ISSUE THREAD

**Issue by TimWanner** [cartologic/cartoview#189]
is it possible to get a short note of wich configurations should be changed to unser GeoNode stand alone from Cargoview in Windows ? (apache config changes and) I'd like to use geocode for itself supporting it to a non profit organisation, for that case there are no cost's allowed, why I would like to use geonode build up for them.

Thanks!

**Comment by ahmednosman** [comment]
you can use the windows installer to install geonode and cartoview on windows. The installer is free and available from http://cartoview.net A new installer will be released within two weeks

**Comment by TimWanner** [comment]
I've downloaded and installed cartoview. I would like to kind of  'extract/delet' out cartoview as I've read about cost's using packages and that cartoview will access them when starting it up. For that reason I thought i could make sure not to have any cost's implemented when only using geonode config parameters - when I provide this as an option to the organization? If I'm wrong please correct me! I would prefer If I could just leave it like default installed and tell them not to use any packages so I would only have to modify the look.

having said this - if I would be wright with 'extracting/deleting' point could these changes run like they are modified ?

--deafult after installation--
WSGIScriptAlias / 'C:/Program Files (x86)/Cartoview/project_template/project_template/wsgi.py'
WSGIPythonPath 'C:/Program Files (x86)/Cartoview/project_template;C:/Program Files (x86)/Cartoview/python/Lib/site-packages'

<Directory 'C:/Program Files (x86)/Cartoview/project_template/project_template'>
<Files wsgi.py>
Require all granted
</Files>
</Directory>

Alias /uploaded 'C:/Program Files (x86)/Cartoview/project_template/uploaded/'
Alias /static 'C:/Program Files (x86)/Cartoview/project_template/static_root/'

<Directory 'C:/Program Files (x86)/Cartoview/project_template/uploaded'>
    Require all granted
</Directory>

<Directory 'C:/Program Files (x86)/Cartoview/project_template/static_root/'>
    Require all granted
</Directory>
--end deafult --

--modified--
WSGIScriptAlias / 'C:/Program Files (x86)/Cartoview/geonode/geonode/wsgi.py'
WSGIPythonPath 'C:/Program Files (x86)/Cartoview/geonode;C:/Program Files   (x86)/Cartoview/python/Lib/site-packages'

<Directory 'C:/Program Files (x86)/Cartoview/geonode/geonode'>
<Files wsgi.py>
Require all granted
</Files>
</Directory>

Alias /uploaded 'C:/Program Files (x86)/Cartoview/geonode/upload/'
Alias /static 'C:/Program Files (x86)/Cartoview/geonode/static/'

<Directory 'C:/Program Files (x86)/Cartoview/geonode/upload'>
    Require all granted
</Directory>

<Directory 'C:/Program Files (x86)/Cartoview/geonode/static'>
    Require all granted
</Directory>
--end -- 

 I'm not sure about the /upload and /static parts, do i have to leave it like default ? and if I change PythonPath to 'geonode' I'd have to change it also in Windows PATH Variable(PythonPath)right? or will they be set with that command ? Would there be a need to add 'Options FollowSymLinks'  for /uploaded as to follow to the documents uploaded ?

Thanks for responding!!
Btw - when you said releasing new installer in two weeks - you mean cargoview or GeoNode ?

**Comment by TimWanner** [comment]
Update: I think I got the point. I can leave all Apache https.conf details as set (use the project_template folder and .wsgi file) and change only local_settings.py when using my own database/passwords/URL swell as Geoserver web.xml, config.xml.

so that only leaves open the 2 question about causing any cost's using this /project_template configuration. ? and the release in two weeks.

cheers

**Comment by ahmednosman** [comment]
there is no cost to using any cartoview software it is all open source

**Comment by TimWanner** [comment]
great! well I'm sorry then.  I got confused about that 'packages' Section on cartoview main page - so there are only costs if the hosting of the website is done via cartoview when I get this right then. 

I guess the Installer release then is meant for Cartoview.
Thanks
