### ISSUE TITLE
1.8.1 Windows Installer

### ISSUE THREAD

**Issue by pjduplooy** [cartologic/cartoview#199]
Hi guys

I am having problems downloading the 1.8.1 Windows Installer.

Upon registering, There is a couple of Python errors.

Please have a look at it, or could you give me an alternate download location.

The 1.7 version also gives the same error.

Pieter

**Comment by hishamkaram** [comment]
FIXED please try again

**Comment by pjduplooy** [comment]
Hi 

Is 1.8.1 not available anymore?

**Comment by hishamkaram** [comment]
@pjduplooy  it's 1.8

**Comment by hishamkaram** [comment]
you can download 1.8 also 1.10 will be available soon

**Comment by pjduplooy** [comment]
hishamkaram

Yesterday when I wanted to download there was a 1.8.1

**Comment by hishamkaram** [comment]
could you check if cartoview 1.8.1 installer available again?

**Comment by pjduplooy** [comment]
Yes, Thank you so much

**Comment by pjduplooy** [comment]
It however still downloads 1.8

**Comment by hishamkaram** [comment]
fixed

**Comment by pjduplooy** [comment]
Thank you...

**Comment by hishamkaram** [comment]
@pjduplooy 1.10 alpha version available

**Comment by pjduplooy** [comment]
hishamkaram

Why are so many apps incompatible in the Windows version (Using 1.10)?
