### ISSUE TITLE
Geoserver

### ISSUE THREAD

**Issue by Cww7** [cartologic/cartoview#2]
Hi,
I'm trying to install cartoview on windows 7 with the windows installer, everything works except Geoserver : no response from the homepage.
Can you help me please ?

**Comment by gmioannou** [comment]
hi,

please check port 4041

Geo

**Comment by ahmednosman** [comment]
Please read the installation instruction and make sure you have the correct
java runtime
http://cartoview.readthedocs.io/en/latest/installation/index.html

login to cartoview as admin/admin
then launch geoserver
http://localhost:4041/geoserver/web/

**Comment by Cww7** [comment]
Java 64 is installed. I also created an inbound rule in the Windows firewall (port 4040, 4041, 5432, 555) but with the netstat -a command the port 4041 does not appear... I don't know why...
Is it possible to set another port for Geoserver ?

**Comment by ahmednosman** [comment]
JDK7 (1.7) or higher must be installed and JAVA_HOME must refer to JDK
directory "C:\Program Files\Java\jdk1.8.0_74"

then  try to restart Tomcat from service manager most probably it is not
started.

**Comment by Cww7** [comment]
It works ! Thanks !!
