### ISSUE TITLE
Linux Installation Problem

### ISSUE THREAD

**Issue by gxcodes** [cartologic/cartoview#3]
Hi, I'm trying to install cartoview on ubuntu server 14.04.4. Geonode is installed and running succesfully (using apt-get install). After I clone cartoview and run 'python setup.py install', it returns an error: Installed distribution OWSLib 0.10.0 conflicts with requirement OWSLib<0.9.0

I've tried uninstall and re-install OWSLib==0.9.0 but the same problem remain. Any suggestion for a proper install on ubuntu server?

**Comment by ahmednosman** [comment]
Dear Kamal
Please help with this installation problem
regards
ahmed

**Comment by gxcodes** [comment]
Not even a clue? Please?

**Comment by kamalseisy** [comment]
Hi,
Sorry for the delay
because you installed geonode, you need to 

> git clone https://github.com/cartologic/cartoview

edit local_settings.py.sample for your correct settings the rename it to local_settings.py

> python manage.py syncdb
> python manage.py runserver

**Comment by gxcodes** [comment]
Hi, I did clone cartoview and run the install script from there. Ok will try to redo the settings, although at this stage now I've managed to install MapLoom directly on top of geonode so maybe no need for cartoview. Thanks for the reply though.

**Comment by jitendrashahiitb** [comment]
I have a choice :use ubuntu 14.04 or 16.04. Some documents suggest 14.04 with geonode version 2.4 and other suggest 16.04 and geonode version to be 2.6a  Can any one suggest what is best in March of 2017 and which install script to follow
Thanks in anticipation

**Comment by jitendrashahiitb** [comment]
![cartoview_geonode_installation_error_in_postgis_connection](https://cloud.githubusercontent.com/assets/4946297/23609997/c4f200e4-0296-11e7-8025-28e19fd12489.png)
Is postgresql and postgis required to be installed before geonode installation? why are they not present before linking to cartoview

**Comment by jitendrashahiitb** [comment]
Where all do I have to edit to add the name of my project?  What changes I have to make in local_settings.py.sample before making it local_settings.py . I did the chhanges in the file as follows : 

![local_settings py](https://cloud.githubusercontent.com/assets/4946297/23610221/cc01c0da-0297-11e7-9a9d-466a343e7a27.png)
It is in /home/jitendra/communitygis/communitygis folder

**Comment by hishamkaram** [comment]
change HOSt from *postgis* to *localhost*
and USERNAME from *postgres* to *<your_database_username> *and PASSWORD to
your *pass*

**Comment by hishamkaram** [comment]
please take a look  [here](http://cartologic.github.io/cartoview/#install-on-ubuntu-linux)

**Comment by jitendrashahiitb** [comment]
The above link 'here' seems to be not working
Is there an updated script for installing on ubuntu 16.04

**Comment by hishamkaram** [comment]
Yes please use this link http://cartologic.github.io

**Comment by jitendrashahiitb** [comment]
Thanks

**Comment by jitendrashahiitb** [comment]
I have a desire to create a project named pocra_test.
I have installed geonode 2.6 
I could also install cartoview.

But what is the exact meaning of 'project' ? If I give my project name as pocra_test as below ( note I am on ubuntu 16.04 and I am using 'django-admin' and not 'django-admin.py'  

 django-admin startproject --template=https://github.com/cartologic/cartoview-project-template/archive/master.zip --name django.env,uwsgi.ini,.bowerrc pocra_test
it executes.

Now 

1. how do I see cartoview apps in geonode interface?
2. How to use cartoview apps on my data loaded in geonode?
