### ISSUE TITLE
Problem install Cartoview in geonode 2.7

### ISSUE THREAD

**Issue by Abdelrhman-Rayis** [cartologic/cartoview#41]
i am working in geonode 2.7 i install it with this doc http://training.geonode.geo-solutions.it/002_install_and_admin/002_geonode_install/index.html
but i am having problem installing cartoview as app or any other app 
when i use this doc https://geonode.readthedocs.io/en/2.0/tutorials/devel/projects/apps.html
 forAdding additional Django apps
i have this Error 
App 'XXX' could not be found. Is it in INSTALLED_APPS?

**Comment by hishamkaram** [comment]
Please Read the [Docs](http://cartologic.github.io/)
