### ISSUE TITLE
Set Localhost to IP_Address

### ISSUE THREAD

**Issue by lolob** [cartologic/cartoview#53]
Hi,

So far cartoview works great. 
How to set the localhost to current_ip? Please look at the attach-pic (orange circle). 
I think because of that my layer data displays big-solid-red-square instead of single-point-pic.
Thanks.

![localhost](https://user-images.githubusercontent.com/15963902/29018471-c87a4ddc-7b8d-11e7-972f-68de3341355f.png)

**Comment by hishamkaram** [comment]
Hello @lolob 
_**if you are using docker :**_ 
open django.env and change `SITEURL` value to your IP and `GEOSERVER_PUBLIC_LOCATION` replace localhost with your Ip 
_**for direct  installation :**_ 
open settings.py and add this variable `SITEURL="http://<your_ip>"` and uncomment the following line 
```
#OGC_SERVER['default']['PUBLIC_LOCATION'] = "http://<your_Ip>:<port_if_any>/geoseerver"
#OGC_SERVER['default']['LOG_FILE'] = os.path.join(BASE_DIR, "geoserver.log")
```

**Comment by lolob** [comment]
Thanks for the notes. I'm okay now.
For feedback on installation docs. I can follow all the instructions very well except when enter this command line `python manage.py makemigrations app_manager`, the message tells to install django-jsonfield-compat .I just follow and install it.

Now, I have problem after installing cartoview_buffer_tool. Error "No module named cartoview_buffer_tool" . Restart and run again the python manage.py runserver. Still the same.

2nd question, How to enable GeoGIG and I would love to use MapLoom too.

Thanks.

**Comment by hishamkaram** [comment]
@lolob in apps folder open `apps.yml` and check if this record exist 
```
- active: true
  name: cartoview_buffer_tool
  order: 25
```
if not please add this record and save
