### ISSUE TITLE
Include Celery Service with CartoView 

### ISSUE THREAD

**Issue by ahmednosman** [cartologic/cartoview#6]
integrate celery service needed to run asynchronous apps like cartoserver

**Comment by dpadron2** [comment]
DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.

![error_cartoview](https://cloud.githubusercontent.com/assets/7448955/21255507/b4f6c15e-c342-11e6-95bb-840f278887a4.jpg)

**Comment by hishamkaram** [comment]
@ahmednosman  @kamalseisy  what is the status of this issue

**Comment by hishamkaram** [comment]
already included in geonode and cartoview
