### ISSUE TITLE
I am facing Reading error when I run cartoview

### ISSUE THREAD

**Issue by ashishSharma7** [cartologic/cartoview#61]
![error](https://user-images.githubusercontent.com/30353072/29980101-d7389a04-8f65-11e7-8dc8-19a4f5caf085.png)
I have installed cartoview in virtual Envireonment locally.
python version 2.7.12
I have followed the instructions available in cartoview for ubuntu
the output looks like
![erroroutput](https://user-images.githubusercontent.com/30353072/29980172-342b018e-8f66-11e7-8217-3e8c397a6b1b.png)

**Comment by hishamkaram** [comment]
please install Shapely1.5.17 using this command : 
`pip install Shapely==1.5.17`
