### ISSUE TITLE
ERROR - App matching query does not exist

### ISSUE THREAD

**Issue by lolob** [cartologic/cartoview#62]
Hello,

I was trying to install app 'cartoview_arcgis_feature_server' . While checking on try.cartoview.net , the new name is CartoServer. Both are the same I think.

**Comment by hishamkaram** [comment]
hello @lolob 
our apps installer is alpha version 
to fix this error please create app object under` APP_MANAGER/Apps` section then click  add `app app button`    in admin panel like in screenshots open apps.yml and add record for cartoserver like this:
```
- active: true
  name: cartoview_arcgis_feature_server
  order: 10
```
![screen shot 2017-09-03 at 6 41 24 am](https://user-images.githubusercontent.com/24391550/30000618-4d2a350c-9073-11e7-8daf-15ff04290273.png)
![screen shot 2017-09-03 at 6 43 47 am](https://user-images.githubusercontent.com/24391550/30000619-4d2ff49c-9073-11e7-964e-113af926c0c0.png)
![screen shot 2017-09-03 at 6 42 07 am](https://user-images.githubusercontent.com/24391550/30000620-4d3774f6-9073-11e7-95c1-57761481f8d0.png)
![screen shot 2017-09-03 at 6 42 19 am](https://user-images.githubusercontent.com/24391550/30000621-4d4f9a54-9073-11e7-80f4-44d641ad42c3.png)
![screen shot 2017-09-03 at 6 42 25 am](https://user-images.githubusercontent.com/24391550/30000622-4d5614ce-9073-11e7-8ba2-8e2d4316ebb3.png)
