### ISSUE TITLE
Ive got an issue when i run python manage.py runserver 0.0.0.0:8000  i get this long error. Someone please help

### ISSUE THREAD

**Issue by NicholasDsouza1996** [cartologic/cartoview#63]
![error1](https://user-images.githubusercontent.com/20857536/30002498-4a0b73b4-909a-11e7-964a-a31c1c60413b.png)
![error2](https://user-images.githubusercontent.com/20857536/30002499-4b2d5b72-909a-11e7-85e0-57e1cdb0447a.png)
![error3](https://user-images.githubusercontent.com/20857536/30002500-4c72c512-909a-11e7-8e8b-e997070ca894.png)

**Comment by lolob** [comment]
@NicholasDsouza1996  python manage.py runserver <your_ip>:8000 
Change <your_ip> into this e:g: 192.168.1.100

For the shapely.geometry import error;
I run this pip install Shapely==1.5.17

**Comment by NicholasDsouza1996** [comment]
is there any file which i have to edit to change my ip?

**Comment by NicholasDsouza1996** [comment]
i tried what uve said ive got a different error

![error4](https://user-images.githubusercontent.com/20857536/30002615-4330cc26-909d-11e7-91ea-c9f0102cae2e.png)

**Comment by lolob** [comment]
1st check what is your local ip. e:g: ifconfig
python manage.py runserver 1 <your_local_ip>:8000 
In the browser enter http://<your_local_ip>:8000
Not http://0.0.0.0:8000

**Comment by hishamkaram** [comment]
@NicholasDsouza1996 please follow steps in [docs](http://cartologic.github.io/installation_ubuntu/) to install cartoview
