### ISSUE TITLE
Unable to run geoserver and authentication error

### ISSUE THREAD

**Issue by Ashish-Sharma-07** [cartologic/cartoview#64]
I am very new to cartoview and geonode. I was trying  to access the geoserver through cartoview but was unable to so i installed geonode using the ppa: geonde/stable repository but now i am getting this error
![cartoviewerror](https://user-images.githubusercontent.com/30353072/30214393-eea84d1a-94c9-11e7-8aa8-cfb91a8e64e1.png)

Please help me out.
@hishamkaram

**Comment by hishamkaram** [comment]
please don't use ppa package to install geonode
use pip to install geonode as python package using this command:
`pip install geonode==2.6.3`
then continue installation by following steps in [docs](http://cartologic.github.io/)

**Comment by ahmednoureldeen** [comment]
@Ashish-Sharma-07 
I hope you managed to install cartoview

**Comment by hishamkaram** [comment]
closed due to lack of response feel free to reopen
