### ISSUE TITLE
Problem for upload data

### ISSUE THREAD

**Issue by acerborealis** [cartologic/cartoview#65]
Hello,
First, I wanted to tell you that your work for extends the popular GeoNode is really cool. I would like to use cartoview with docker on a vitualbox (Ubuntu 16.04LTS). I am a beginner. 
Could you help me please ?
I installed as stated in your website https://cartologic.github.io/installation_docker/ and just run it but when I want to add layers nothing works.
when I connect to geoserver I see the data in the table, but when I want to view the data in geoserver I have a page with error.
Please tell me why I don't see the added data in the application, please.

**Comment by acerborealis** [comment]
Can someone please help me?

**Comment by hishamkaram** [comment]
please can you provide me with error message @acerborealis

**Comment by acerborealis** [comment]
For add data in the application, I click on Data and after Upload layer on top menu.
I click on Choose Files and I Choose all files I want to add and I click on open.
![01](https://user-images.githubusercontent.com/21114517/30250381-a68fe760-964d-11e7-9664-c1d3b6b5f577.png)


I click on Upload files and I assume that the data has been uploaded (is it normal the pale yellow box that appeared?)
![02](https://user-images.githubusercontent.com/21114517/30250393-c1ebb296-964d-11e7-9137-690c456b03ea.png)


After I click on Data and layers on top menu for access to the data page. Nothing appears in the list.
![03](https://user-images.githubusercontent.com/21114517/30250397-d76b770a-964d-11e7-8606-30bed3dfa5c5.png)


But when I connect to Geoserver, I can see the data that was added.
![04](https://user-images.githubusercontent.com/21114517/30250403-e6917e6e-964d-11e7-9a2b-5cb5c6b73826.png)


What is the problem, please ?


Also, I tried to add a shapefile of 146mo, and when I want to add them I have an error. What can I do to not have this error please ?
![5](https://user-images.githubusercontent.com/21114517/30250406-ef701e00-964d-11e7-9f52-b2c272339c5f.png)

Can you help me with these 2 problems, please?

**Comment by acerborealis** [comment]
Normally I should have this after uploading the data
![06](https://user-images.githubusercontent.com/21114517/30251191-fcaf57ae-965a-11e7-9e22-2179a7a9c57f.png)
What do I have to do to make it work, please?

In geoserver, the layer is in shapefile form. Is it possible to host layers in PostGIS and not in shapefile?
What is the best? I think is to use PostGIS.
![07](https://user-images.githubusercontent.com/21114517/30251227-c407fd4c-965b-11e7-9826-ebeb0cc5c576.png)

**Comment by hishamkaram** [comment]
@acerborealis you need to [configure geoserver](http://docs.geonode.org/en/master/tutorials/admin/geoserver_geonode_security/#geoserver-security-backend)

**Comment by acerborealis** [comment]
I checked everything that is marked in the GeoServer Security Backend paragraph. So, I did not configure anything because everything is correct as explained in the document.
If Geoserver is configured correctly, where does the problem come from?

**Comment by acerborealis** [comment]
Can someone please help me with a great idea ?

**Comment by hishamkaram** [comment]
it seems geoserver is not running please check if geoserver is running and check the following variables in `settings.py `
```
GC_SERVER['default']['PUBLIC_LOCATION'] = "<geoserver_public_url>"
OGC_SERVER['default']['LOCATION'] ="<geoserver_local_url>"
```

**Comment by acerborealis** [comment]
When I use http://localhost/geoserver/web/, I can connect me to geoserver.
Where can I find the file settings.py?
Thx

**Comment by hishamkaram** [comment]
in your project folder you will find a folder with the same name  contains `settings.py`

**Comment by acerborealis** [comment]
except:
    pass
#OGC_SERVER['default']['LOCATION'] = GEOSERVER_LOCATION
#OGC_SERVER['default']['PUBLIC_LOCATION'] = GEOSERVER_PUBLIC_LOCATION
#OGC_SERVER['default']['LOG_FILE'] = os.path.join(BASE_DIR, "geoserver.log")

**Comment by acerborealis** [comment]
try:
    from pre_settings import *
except:
    pass
import os
import cartoview


PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(PROJECT_DIR)
cartoview_settings_path = os.path.join(os.path.dirname(cartoview.__file__), 'settings.py')
execfile(cartoview_settings_path)
#bower static files
STATICFILES_DIRS += [os.path.join(PROJECT_DIR, "static"),]
#django Media Section
#uncomment the following if you want your files out of geonode folder
MEDIA_ROOT = os.path.join(BASE_DIR, "uploaded")
MEDIA_URL = "/uploaded/"
LOCAL_MEDIA_URL = "/uploaded/"
#static section
STATIC_ROOT = os.path.join(BASE_DIR, "static")
ALLOWED_HOSTS =['*']
try:
    from local_settings import *
except:
    pass
#OGC_SERVER['default']['LOCATION'] = GEOSERVER_LOCATION
#OGC_SERVER['default']['PUBLIC_LOCATION'] = GEOSERVER_PUBLIC_LOCATION
#OGC_SERVER['default']['LOG_FILE'] = os.path.join(BASE_DIR, "geoserver.log")
if 'datastore' in DATABASES:
  OGC_SERVER['default']['DATASTORE'] = 'datastore'

MIDDLEWARE_CLASSES += ( "django.middleware.gzip.GZipMiddleware",)

if 'geonode.geoserver' in INSTALLED_APPS and "LOCAL_GEOSERVER" in locals() and LOCAL_GEOSERVER in MAP_BASELAYERS:
       LOCAL_GEOSERVER["source"]["url"] = OGC_SERVER['default']['PUBLIC_LOCATION'] + "wms"


#uncomment the following to enable geonode client
#INSTALLED_APPS += ('geonode-client',)
#LAYER_PREVIEW_LIBRARY="react"


#uncomment the following to enable osgeo_importer
#INSTALLED_APPS += ('osgeo_importer',)
#DATABASES['datastore']= {
#        'ENGINE': 'django.contrib.gis.db.backends.postgis',
#        'NAME': 'cartoview_datastore',
#        'USER' : 'cartologic',
#        'PASSWORD' : 'root',
#        'HOST' : 'postgis',
#        'PORT' : '5432',
#}
#### osgeo_importer settings
#OSGEO_DATASTORE = 'datastore'
#OSGEO_IMPORTER_GEONODE_ENABLED = True
#OSGEO_IMPORTER_VALID_EXTENSIONS = [
#    'shp', 'shx', 'prj', 'dbf', 'kml', 'geojson', 'json', 'tif', 'tiff',
#    'gpkg', 'csv', 'zip', 'xml', 'sld'
#]
#IMPORT_HANDLERS = [
    # If GeoServer handlers are enabled, you must have an instance of geoserver running.
    # Warning: the order of the handlers here matters.
#    'osgeo_importer.handlers.FieldConverterHandler',
#    'osgeo_importer.handlers.geoserver.GeoserverPublishHandler',
#    'osgeo_importer.handlers.geoserver.GeoserverPublishCoverageHandler',
#    'osgeo_importer.handlers.geoserver.GeoServerTimeHandler',
#    'osgeo_importer.handlers.geoserver.GeoWebCacheHandler',
#    'osgeo_importer.handlers.geoserver.GeoServerBoundsHandler',
#    'osgeo_importer.handlers.geoserver.GenericSLDHandler',
#    'osgeo_importer.handlers.geonode.GeoNodePublishHandler',
#     'osgeo_importer.handlers.mapproxy.publish_handler.MapProxyGPKGTilePublishHandler',
#    'osgeo_importer.handlers.geoserver.GeoServerStyleHandler',
#    'osgeo_importer.handlers.geonode.GeoNodeMetadataHandler'
#]

#PROJECTION_DIRECTORY = os.path.join(PROJECT_ROOT, "data")

**Comment by hishamkaram** [comment]
add the following line in you settings.py after replacing `<your_geoserver_local_url>` and `<YOUR_GEOSERVER_PUBLIC_LOCATION>` with the proper url
```
OGC_SERVER['default']['LOCATION'] = <your_geoserver_local_url>
OGC_SERVER['default']['PUBLIC_LOCATION'] = <YOUR_GEOSERVER_PUBLIC_LOCATION>
```

**Comment by hishamkaram** [comment]
`<your_geoserver_local_url>` should be something like this `http://localhost:8080/geoserver/`
and `<YOUR_GEOSERVER_PUBLIC_LOCATION>` something like this `http://localhost/geoserver/`

**Comment by acerborealis** [comment]
Then it will look like this ?
...
except:
    pass
OGC_SERVER['default']['LOCATION'] = 'http://localhost:8080/geoserver/'
OGC_SERVER['default']['PUBLIC_LOCATION'] = 'http://localhost/geoserver/'
#OGC_SERVER['default']['LOG_FILE'] = os.path.join(BASE_DIR, "geoserver.log")
if 'datastore' in DATABASES:
...

**Comment by acerborealis** [comment]
It doesn't work, always the same. Too I have nothing that appears in geoserver in the layers section.
I still have the same problem.

**Comment by hishamkaram** [comment]
please follow steps in [docs](http://cartologic.github.io/) don't skip step or section

**Comment by acerborealis** [comment]
I don't understand where the problem is? I have reinstalled several times ubuntu 16.04LTS + cartoview, I read and reread the document online (https://cartologic.github.io/installation_docker/), but every time I still have the same problem: I can not upload data as explained above. Can you help me please, because I don't know what to do to make everything work correctly? Please

**Comment by acerborealis** [comment]
Here are the commands that I execute from a new installation of Ubuntu 16.04LTS (not in root mode):
```
sudo apt-get upgrade
sudo apt-get update
```
I restart the computer
```
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install docker-ce
sudo docker run hello-world
sudo groupadd docker
sudo usermod -aG docker $USER
sudo curl -L --fail https://github.com/docker/compose/releases/download/1.15.0/run.sh -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
django-admin startproject --template=https://github.com/cartologic/cartoview-project-template/archive/master.zip --name django.env,uwsgi.ini,.bowerrc,server.py portal
cd portal/
sudo -s
make run
 ```
When finished, I open firefox and I use : http://localhost for open the website, after I try to upload data as explained above, but I have always the same problem and I can't appreciate cartoview

**Comment by acerborealis** [comment]
Can someone please help me?

**Comment by acerborealis** [comment]
Can anyone tell me if I made a mistake in my ubuntu installation, docker installation, cartoview installation, ...
I keep looking on the web, reinstall the applications as stated above, but I can not find the solution.
Can someone please help me with a great idea for help me, please ?

**Comment by hishamkaram** [comment]
hello @acerborealis 
sorry for being late , can you open terminal in ubuntu and go to portal folder and execute the following command 
`docker-compose logs --follow --tail=100 cartoview `
then try to upload layer and send me output in terminal
thanks

**Comment by acerborealis** [comment]
Thank you for your answer. I hope you will find the problem. Here is the output in terminal :

Attaching to geocarto_cartoview_1
cartoview_1  | [17/Sep/2017:12:57:12] ENGINE Bus STARTING
cartoview_1  | [17/Sep/2017:12:57:12] ENGINE Started monitor thread 'Autoreloader'.
cartoview_1  | [17/Sep/2017:12:57:12] ENGINE Started monitor thread '_TimeoutMonitor'.
cartoview_1  | [17/Sep/2017:12:57:12] ENGINE Serving on http://0.0.0.0:8000
cartoview_1  | [17/Sep/2017:12:57:12] ENGINE Bus STARTED
cartoview_1  | [17/Sep/2017:13:02:36] ENGINE Bus STARTING
cartoview_1  | [17/Sep/2017:13:02:36] ENGINE Started monitor thread 'Autoreloader'.
cartoview_1  | [17/Sep/2017:13:02:36] ENGINE Started monitor thread '_TimeoutMonitor'.
cartoview_1  | [17/Sep/2017:13:02:36] ENGINE Serving on http://0.0.0.0:8000
cartoview_1  | [17/Sep/2017:13:02:36] ENGINE Bus STARTED
cartoview_1  | 
cartoview_1  | Traceback (most recent call last):
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/layers/views.py", line 168, in layer_upload
cartoview_1  |     metadata_uploaded_preserve=form.cleaned_data["metadata_uploaded_preserve"]
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 499, in file_upload
cartoview_1  |     defaults=defaults
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
cartoview_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/modeltranslation/manager.py", line 389, in get_or_create
cartoview_1  |     return super(MultilingualQuerySet, self).get_or_create(**kwargs)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 407, in get_or_create
cartoview_1  |     return self._create_object_from_params(lookup, params)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 439, in _create_object_from_params
cartoview_1  |     obj = self.create(**params)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/modeltranslation/manager.py", line 381, in create
cartoview_1  |     return super(MultilingualQuerySet, self).create(**kwargs)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 348, in create
cartoview_1  |     obj.save(force_insert=True, using=self.db)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/polymorphic/models.py", line 74, in save
cartoview_1  |     return super(PolymorphicModel, self).save(*args, **kwargs)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
cartoview_1  |     force_update=force_update, update_fields=update_fields)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 758, in save_base
cartoview_1  |     update_fields=update_fields)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 189, in send
cartoview_1  |     response = receiver(signal=self, sender=sender, **named)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/signals.py", line 93, in geoserver_pre_save
cartoview_1  |     charset=instance.charset)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 1197, in geoserver_upload
cartoview_1  |     sld = get_sld_for(cat, publishing)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 190, in get_sld_for
cartoview_1  |     if layer.default_style is None:
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geoserver/layer.py", line 127, in _get_default_style
cartoview_1  |     return self._resolve_style(element) if element is not None else None
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geoserver/layer.py", line 135, in _resolve_style
cartoview_1  |     return self.catalog.get_style_by_url(style_workspace_url)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 797, in get_style_by_url
cartoview_1  |     dom = self.get_xml(style_workspace_url)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 211, in get_xml
cartoview_1  |     response, content = self.http.request(rest_url)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1659, in request
cartoview_1  |     (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1399, in _request
cartoview_1  |     (response, content) = self._conn_request(conn, request_uri, method, body, headers)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1355, in _conn_request
cartoview_1  |     response = conn.getresponse()
cartoview_1  |   File "/usr/lib/python2.7/httplib.py", line 1123, in getresponse
cartoview_1  |     raise ResponseNotReady()
cartoview_1  | ResponseNotReady
cartoview_1  | 
cartoview_1  | Traceback (most recent call last):
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/layers/views.py", line 168, in layer_upload
cartoview_1  |     metadata_uploaded_preserve=form.cleaned_data["metadata_uploaded_preserve"]
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/layers/utils.py", line 499, in file_upload
cartoview_1  |     defaults=defaults
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
cartoview_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/modeltranslation/manager.py", line 389, in get_or_create
cartoview_1  |     return super(MultilingualQuerySet, self).get_or_create(**kwargs)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 407, in get_or_create
cartoview_1  |     return self._create_object_from_params(lookup, params)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 439, in _create_object_from_params
cartoview_1  |     obj = self.create(**params)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/modeltranslation/manager.py", line 381, in create
cartoview_1  |     return super(MultilingualQuerySet, self).create(**kwargs)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 348, in create
cartoview_1  |     obj.save(force_insert=True, using=self.db)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/polymorphic/models.py", line 74, in save
cartoview_1  |     return super(PolymorphicModel, self).save(*args, **kwargs)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
cartoview_1  |     force_update=force_update, update_fields=update_fields)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 758, in save_base
cartoview_1  |     update_fields=update_fields)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 189, in send
cartoview_1  |     response = receiver(signal=self, sender=sender, **named)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/signals.py", line 93, in geoserver_pre_save
cartoview_1  |     charset=instance.charset)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 1197, in geoserver_upload
cartoview_1  |     sld = get_sld_for(cat, publishing)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", line 190, in get_sld_for
cartoview_1  |     if layer.default_style is None:
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geoserver/layer.py", line 127, in _get_default_style
cartoview_1  |     return self._resolve_style(element) if element is not None else None
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geoserver/layer.py", line 135, in _resolve_style
cartoview_1  |     return self.catalog.get_style_by_url(style_workspace_url)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 797, in get_style_by_url
cartoview_1  |     dom = self.get_xml(style_workspace_url)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 211, in get_xml
cartoview_1  |     response, content = self.http.request(rest_url)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1659, in request
cartoview_1  |     (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1399, in _request
cartoview_1  |     (response, content) = self._conn_request(conn, request_uri, method, body, headers)
cartoview_1  |   File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1355, in _conn_request
cartoview_1  |     response = conn.getresponse()
cartoview_1  |   File "/usr/lib/python2.7/httplib.py", line 1123, in getresponse
cartoview_1  |     raise ResponseNotReady()
cartoview_1  | ResponseNotReady

**Comment by acerborealis** [comment]
Hello @hishamkaram thank you for your help.
I wanted to know if you found anything after sending the code output in terminal.
Do I have to send you more informations?
I'm really looking forward to debugging the installation to use cartoview

**Comment by acerborealis** [comment]
Hi, 
Today I wanted to reinstall the container on my ubuntu virtualbox and now I have this error after typing make run:
```
# bring up the services
docker-compose up -d
geoportail_postgis_1 is up-to-date
geoportail_geoserver_1 is up-to-date
geoportail_cartoview_1 is up-to-date
geoportail_nginx_1 is up-to-date
sleep 5
docker-compose exec cartoview python manage.py makemigrations app_manager
ERROR: Container d5d134b5103d2c213ad43ed818c8cc5dc39331cd2efec00ef907f46033f6ec7d is restarting, wait until the container is running
Makefile:16 : la recette pour la cible « prepare_manager » a échouée
make: *** [prepare_manager] Erreur 1
```

**Comment by acerborealis** [comment]
Hi,
I can not find the solution.
Can someone please help me with a great idea for help me, please ?

**Comment by hishamkaram** [comment]
hello @acerborealis 
please recreate the project, this issue already fixed
