### ISSUE TITLE
arcportal_home

### ISSUE THREAD

**Issue by lolob** [cartologic/cartoview#73]
Hi,

I installed three apps (ArcGIS Basic Viewer, ArcGIS Minimalist Viewer, Public Information ). All of them gives an error "arcportal_home" not found during test.

**Comment by ahmednosman** [comment]
these apps require cartoportal to be installed

**Comment by lolob** [comment]
@ahmednosman Thanks.

But now I get this when testing ArcGIS Basic Viewer; 

[21/Sep/2017 04:43:02] "GET /apps/cartoview_arcgis_feature_server/portal/portal/sharing/rest/search?q=(group%3A%222f0ec8cb03574128bd673cefab106f39%22)%20%20-type%3A%22Attachment%22&start=1&num=9 HTTP/1.1" 500 28704

**Comment by hishamkaram** [comment]
please after installing feature server execute the following commands:
```
python manage.py makemigrations cartoserver
python manage.py migrate cartoserver
python manage.py makemigrations arcportal
python manage.py migrate arcportal
python manage.py makemigrations cartoportal
python manage.py migrate cartoportal
```
