### ISSUE TITLE
Error While Installing an app

### ISSUE THREAD

**Issue by khaledboka** [cartologic/cartoview#85]
While installing any app, Sometimes this happens, Apparently slow network could be a reason
<img width="1440" alt="screen shot 2017-11-26 at 4 47 13 pm" src="https://user-images.githubusercontent.com/13452248/33256668-b501e3d4-d35b-11e7-853c-db09c945d21e.png">
This shows the error 502 bad gateway in the console, but the user doesn't see the error in the page

However, If the page reloaded you will see the app installed normally
<img width="1438" alt="screen shot 2017-11-26 at 4 48 11 pm" src="https://user-images.githubusercontent.com/13452248/33256716-f013c92e-d35b-11e7-8df0-48ee98bbf4a6.png">

**Comment by hishamkaram** [comment]
closed due to lack of response please feel free to reopen if you provide required information (log, cartoview version, geonode version ,etc)
