### ISSUE TITLE
No Loading Indicator

### ISSUE THREAD

**Issue by khaledboka** [cartologic/cartoview#86]
While loading the list of apps , There is no loading indicator and the Footer got too large

<img width="938" alt="screen shot 2017-11-27 at 10 21 14 am" src="https://user-images.githubusercontent.com/13452248/33256951-f65e2986-d35c-11e7-9ac8-5a52adbcea84.png">

**Comment by hishamkaram** [comment]
PR: https://github.com/cartologic/cartoview/pull/105
