### ISSUE TITLE
Uninstallation of app that considered dependency for other apps

### ISSUE THREAD

**Issue by khaledboka** [cartologic/cartoview#89]
Note/Suggestion
Ex: At 'Simple Map Viewer' uninstallation 
please consider the following note at the confirmation dialog or any similar note:

"This app considered dependency for the following apps, This will remove the app "simple map viewer" and the following apps"

**Comment by hishamkaram** [comment]
this the correct behavior because if you removed the app , all apps which depend on this application won't work
